import { AlertCircle, LoaderCircle, RefreshCw } from 'lucide-react'
import { cn } from '@/lib/utils'

export function Skeleton({className}:{className?:string}){return <span aria-hidden="true" className={cn('block animate-pulse rounded-md bg-muted motion-reduce:animate-none',className)}/>} 

export function TableSkeleton({rows=6}:{rows?:number}){return <div role="status" aria-label="Loading records" className="overflow-hidden rounded-lg border border-border"><div className="flex gap-5 border-b border-border bg-muted/20 p-4">{['w-28','w-20','w-16','w-14','w-12'].map((width,index)=><Skeleton key={index} className={`h-3 ${width}`}/>)}</div><div className="divide-y divide-border">{Array.from({length:rows}).map((_,index)=><div key={index} className="grid grid-cols-[42px_1.5fr_1fr_1fr_100px] items-center gap-4 p-4"><Skeleton className="size-8 rounded-full"/><div className="space-y-2"><Skeleton className="h-3 w-4/5"/><Skeleton className="h-2.5 w-2/5"/></div><Skeleton className="h-3 w-3/4"/><Skeleton className="h-3 w-2/3"/><Skeleton className="h-7 w-20"/></div>)}</div><span className="sr-only">Loading records…</span></div>}

export function PageSkeleton(){return <div role="status" aria-label="Loading page" className="space-y-6"><div className="space-y-3"><Skeleton className="h-7 w-56"/><Skeleton className="h-3 w-full max-w-xl"/></div><div className="grid grid-cols-2 gap-3 md:grid-cols-4"><Skeleton className="h-24"/><Skeleton className="h-24"/><Skeleton className="h-24"/><Skeleton className="h-24"/></div><TableSkeleton/><span className="sr-only">Loading TRACE…</span></div>}

export function ErrorState({title='Unable to load this page',description='TRACE could not retrieve this information right now.',onRetry,compact=false}:{title?:string;description?:string;onRetry?:()=>void;compact?:boolean}){return <div role="alert" className={cn('flex flex-col items-center justify-center rounded-lg border border-destructive/20 bg-destructive/5 px-6 text-center',compact?'min-h-40 py-8':'min-h-72 py-12')}><span className="flex size-10 items-center justify-center rounded-full bg-destructive/10 text-destructive"><AlertCircle className="size-5"/></span><h2 className="mt-4 text-sm font-semibold">{title}</h2><p className="mt-1 max-w-md text-xs leading-5 text-muted-foreground">{description}</p>{onRetry&&<button onClick={onRetry} className="mt-4 inline-flex h-9 items-center gap-2 rounded-md border border-border bg-background px-4 text-xs font-semibold"><RefreshCw className="size-3.5"/> Try Again</button>}</div>}

export function LoadingButton({loading,children,className,disabled,...props}:React.ButtonHTMLAttributes<HTMLButtonElement>&{loading?:boolean}){return <button disabled={disabled||loading} className={cn('inline-flex items-center justify-center gap-2 disabled:cursor-not-allowed disabled:opacity-60',className)} {...props}>{loading&&<LoaderCircle className="size-3.5 animate-spin motion-reduce:animate-none"/>}{loading?'Processing…':children}</button>}
