import { CheckCircle2, Download, FileSpreadsheet, FileText, Presentation, TrendingDown, TrendingUp } from 'lucide-react'
import { FinalCta, HeroActions, ProductPreview, SectionHeading, marketingContainer } from '@/components/marketing/marketing-ui'

const includes=['Executive summary','Audit score and trend','Findings by severity','Detailed observations','Recommendations and actions','Evidence and supporting data','Appendices and methodology']

export default function ReportsPage(){return <>
  <section className="border-b border-border"><div className={`${marketingContainer} grid items-center gap-12 py-16 lg:grid-cols-[.7fr_1.3fr] lg:py-20`}><div><p className="text-xs font-bold uppercase tracking-[.14em] text-brand">Reports</p><h1 className="mt-4 text-4xl font-bold leading-[1.08] tracking-tight sm:text-5xl">Reports that drive clarity and action.</h1><p className="mt-5 text-base leading-7 text-muted-foreground">TRACE turns audit data into clear, professional reports that help you communicate findings, track progress and prove impact to every client.</p><ul className="mt-6 space-y-3">{['Professional, branded reports in minutes','Data-driven insights and visualisations','Export and share securely'].map(item=><li key={item} className="flex items-center gap-2 text-sm"><CheckCircle2 className="size-4 text-brand"/>{item}</li>)}</ul><HeroActions secondary="See a sample report" secondaryHref="#sample-report"/></div><ProductPreview mode="report"/></div></section>
  <section className={`${marketingContainer} py-20`}><SectionHeading title="Powerful reporting. Built for consultants." description="Everything you need to communicate findings, track improvement and deliver measurable value."/><div className="mx-auto mt-12 max-w-5xl space-y-5">
    <ReportRow title="Professional reports in minutes" description="Generate clean, branded reports that are ready to share with your clients. Include summaries, scores, findings, recommendations and next steps automatically."><div className="rounded-lg border border-border p-5"><div className="flex justify-between"><div><p className="text-xs font-bold">Website Audit Report</p><p className="mt-1 text-[10px] text-muted-foreground">Oak & Pixel · 20 August 2026</p></div><span className="text-[10px] font-bold tracking-[.25em]">TRACE</span></div><div className="mt-5 grid grid-cols-[1fr_auto] gap-6"><div><p className="text-[10px] font-bold">Executive Summary</p><p className="mt-2 text-[9px] leading-4 text-muted-foreground">A clear view of strengths, risks and recommended priorities for improvement.</p></div><div className="inline-flex size-16 items-center justify-center rounded-full border-[5px] border-success text-xl font-bold">78</div></div></div></ReportRow>
    <ReportRow title="Visual insights that matter" description="Clear charts and visualisations help you quickly identify trends, risks and opportunities across audits and over time."><div className="grid gap-3 sm:grid-cols-2"><MiniTrend/><SeverityDonut/></div></ReportRow>
    <ReportRow title="Track progress over time" description="Compare baseline audits with reassessments to demonstrate improvement and prove the impact of your recommendations."><ComparisonTable/></ReportRow>
    <ReportRow title="Export and share with ease" description="Export reports to PDF, PowerPoint or Excel. Share securely with clients or your team with a single link."><div className="grid gap-3 sm:grid-cols-3">{[[FileText,'PDF','Best for printing'],[Presentation,'PowerPoint','Best for presentations'],[FileSpreadsheet,'Excel','Best for data analysis']].map(([Icon,title,desc])=><button type="button" key={title as string} className="flex items-center gap-3 rounded-lg border border-border p-4 text-left transition-colors hover:border-brand"><Icon className="size-5 text-brand"/><span><strong className="block text-xs">{title as string}</strong><span className="text-[10px] text-muted-foreground">{desc as string}</span></span></button>)}</div></ReportRow>
  </div></section>
  <section id="sample-report" className={`${marketingContainer} grid gap-8 py-12 lg:grid-cols-[.75fr_1.25fr]`}><div><h2 className="text-xl font-bold">Every report includes</h2><ul className="mt-5 space-y-3">{includes.map(item=><li key={item} className="flex gap-2 text-sm"><CheckCircle2 className="size-4 shrink-0 text-brand"/>{item}</li>)}</ul></div><div className="flex flex-col justify-between rounded-xl border border-border bg-muted/20 p-7 sm:flex-row sm:items-center"><div><h2 className="text-xl font-bold">See it in action</h2><p className="mt-3 max-w-sm text-sm leading-6 text-muted-foreground">Preview how TRACE turns audit results into a polished client-ready story.</p><button type="button" className="mt-6 inline-flex h-11 items-center gap-2 rounded-lg border border-border bg-white px-5 text-sm font-semibold hover:bg-muted"><Download className="size-4"/>Download sample report</button></div><div className="mt-8 w-44 rounded-lg border border-border bg-white p-5 shadow-sm sm:mt-0"><p className="text-[10px] font-bold tracking-[.25em]">TRACE</p><p className="mt-10 text-xs font-bold">Website Audit Report</p><div className="mt-4 h-20 rounded bg-slate-950"/></div></div></section>
  <FinalCta title="Reports that help you deliver more value." description="Join leading consulting firms using TRACE to deliver clear, professional and impactful audit reports."/>
  </>}

function ReportRow({title,description,children}:{title:string;description:string;children:React.ReactNode}){return <article className="grid overflow-hidden rounded-xl border border-border lg:grid-cols-[280px_1fr]"><div className="border-b border-border p-6 lg:border-b-0 lg:border-r"><h3 className="text-lg font-bold">{title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{description}</p></div><div className="p-5">{children}</div></article>}
function MiniTrend(){return <div className="rounded-lg border border-border p-4"><p className="text-xs font-semibold">Score Trend</p><svg viewBox="0 0 220 90" className="mt-2 h-24 w-full"><path d="M5 75L42 48L78 54L115 34L151 43L188 20L215 24" fill="none" stroke="currentColor" strokeWidth="2.5"/></svg></div>}
function SeverityDonut(){return <div className="flex items-center gap-6 rounded-lg border border-border p-4"><div className="size-24 rounded-full" style={{background:'conic-gradient(#ef5226 0 16%,#f59e0b 16% 48%,#fbbf24 48% 74%,#86efac 74% 100%)'}}><div className="m-5 size-14 rounded-full bg-white"/></div><div className="space-y-2 text-[10px]"><p><b>5</b> Critical</p><p><b>12</b> High</p><p><b>18</b> Medium</p><p><b>7</b> Low</p></div></div>}
function ComparisonTable(){const rows=[['Audit Score','64','78','+14','up'],['Critical Issues','7','5','-2','down'],['High Issues','15','12','-3','down'],['Recommendations','30','24','-6','down']] as const;return <div className="overflow-x-auto rounded-lg border border-border"><table className="w-full min-w-[540px] text-left text-xs"><thead className="bg-muted/60"><tr>{['Metric','Baseline','Result','Change'].map(h=><th key={h} className="px-4 py-3 font-semibold">{h}</th>)}</tr></thead><tbody>{rows.map(([metric,baseline,result,change,direction])=><tr key={metric} className="border-t border-border"><td className="px-4 py-3 font-medium">{metric}</td><td className="px-4 py-3">{baseline}</td><td className="px-4 py-3">{result}</td><td className="px-4 py-3 font-semibold text-success"><span className="inline-flex items-center gap-1">{change}{direction==='up'?<TrendingUp className="size-3"/>:<TrendingDown className="size-3"/>}</span></td></tr>)}</tbody></table></div>}
