import type { AuditTypeDefinition } from '@/types/audit-type-definition'

const sharedTabs = ['Overview','Collection','Findings','Recommendations','Actions','Evidence','Workpapers','Review','Reports','Planning','Reassessment','Activity'] as const

export const AUDIT_TYPES = [
  {
    id:'website', name:'Website Audit', icon:'website', description:'Review performance, accessibility, SEO, content and overall website quality.',
    capabilities:['automated-scan','evidence','analysis','findings','recommendations','reassessment'],
    detailFields:[{id:'websiteUrl',label:'Website URL',type:'url',placeholder:'https://oakandpixel.co.za',required:true},{id:'primaryDomain',label:'Primary Domain',type:'text',placeholder:'oakandpixel.co.za',required:true},{id:'environment',label:'Environment',type:'select',options:['Production','Staging','Development','Other']}],
    scopeFields:[{id:'startUrl',label:'Start URL',type:'url',placeholder:'https://oakandpixel.co.za',required:true},{id:'includedDomains',label:'Included Domains',type:'multi-entry',placeholder:'Add a domain'},{id:'includedPaths',label:'Included Pages / Paths',type:'multi-entry',placeholder:'/services'},{id:'excludedPaths',label:'Excluded Pages / Paths',type:'multi-entry',placeholder:'/admin'},{id:'crawlDepth',label:'Crawl Depth',type:'number',placeholder:'3'},{id:'maximumPages',label:'Maximum Pages',type:'number',placeholder:'250'},{id:'devices',label:'Audit Devices',type:'multi-select',options:['Mobile Audit','Desktop Audit']},{id:'crawlOptions',label:'Crawl Options',type:'multi-select',options:['Include Subdomains','Follow External Links','Authentication Required']}],
    collectionAreas:['Automated Scan','On-Page Analysis','Performance','Accessibility','Mobile Experience','Security','Content Review','Link Analysis'], supportedTabs:['Overview','Collection','Findings','Recommendations','Actions','Evidence','Workpapers','Review','Reports','Planning','Technical Details','Reassessment','Activity'], compatibleFrameworks:['fwk-web-001'], requiredEvidenceTypes:['Screenshot','Report','Data','URL'], stakeholderLabels:['Technical Owner','Content Owner','Reviewer'], scoringEnabled:true,
  },
  {
    id:'brand', name:'Brand Consistency Audit', icon:'brand', description:'Assess brand identity, consistency, messaging and visual expression.',
    capabilities:['questionnaire','evidence','consultant-observations','analysis','findings','recommendations','reassessment'],
    detailFields:[{id:'brandName',label:'Brand Name',type:'text',placeholder:'Oak & Pixel',required:true},{id:'primaryMarket',label:'Primary Market',type:'text',placeholder:'South Africa'},{id:'businessUnit',label:'Brand / Business Unit',type:'text',placeholder:'Corporate Brand'}],
    scopeFields:[{id:'touchpoints',label:'Brand Touchpoints',type:'multi-select',options:['Logo','Brand Guidelines','Colour System','Typography','Messaging','Tone of Voice','Website','Social Media','Email Signatures','Presentations','Documents','Marketing Collateral','Photography','Video','Physical Signage','Other'],required:true},{id:'channels',label:'Channels',type:'multi-entry',placeholder:'Add a channel'},{id:'businessUnits',label:'Business Units',type:'multi-entry',placeholder:'Add a business unit'},{id:'locations',label:'Locations',type:'multi-entry',placeholder:'Add a location'},{id:'markets',label:'Markets',type:'multi-entry',placeholder:'Add a market'},{id:'products',label:'Products / Services',type:'multi-entry',placeholder:'Add a product or service'}],
    collectionAreas:['Brand Identity','Logo Usage','Colour Consistency','Typography','Messaging','Tone of Voice','Website Brand Application','Social Media','Documents & Presentations','Marketing Collateral','Photography & Imagery','Physical Touchpoints'], supportedTabs:sharedTabs, compatibleFrameworks:['fwk-brn-001'], requiredEvidenceTypes:['Image','Document','Screenshot','Video'], stakeholderLabels:['Brand Owner','Marketing Stakeholder','Reviewer'], scoringEnabled:true,
  },
  {
    id:'digital-presence', name:'Digital Presence Audit', icon:'digital', description:'Evaluate reach, channel consistency and digital discoverability.',
    capabilities:['automated-scan','questionnaire','evidence','consultant-observations','analysis','findings','recommendations','reassessment'],
    detailFields:[{id:'primaryBrand',label:'Primary Brand / Organisation Name',type:'text',placeholder:'Oak & Pixel',required:true},{id:'primaryWebsite',label:'Primary Website',type:'url',placeholder:'https://oakandpixel.co.za'},{id:'primaryMarket',label:'Primary Market',type:'text',placeholder:'South Africa'}],
    scopeFields:[{id:'channels',label:'Digital Channels',type:'multi-select',options:['Website','Google Business Profile','Google Search','LinkedIn','Instagram','Facebook','TikTok','YouTube','X / Twitter','Review Platforms','Industry Directories','Other'],required:true},{id:'profileUrls',label:'Profile URLs',type:'multi-entry',placeholder:'Add a profile URL'},{id:'competitors',label:'Competitors',type:'multi-entry',placeholder:'Add a competitor'},{id:'geographicMarket',label:'Geographic Market',type:'text',placeholder:'Johannesburg, South Africa'},{id:'targetAudience',label:'Target Audience',type:'textarea',placeholder:'Describe the primary audience'},{id:'keywords',label:'Search Terms / Keywords',type:'multi-entry',placeholder:'Add a keyword'}],
    collectionAreas:['Website Presence','Search Visibility','Google Business Profile','LinkedIn','Instagram','Facebook','TikTok','YouTube','Review Platforms','Directories','Cross-Channel Consistency','Reputation Signals'], supportedTabs:sharedTabs, compatibleFrameworks:['fwk-dig-001','fwk-sec-001'], requiredEvidenceTypes:['Screenshot','Data','URL','Report'], stakeholderLabels:['Marketing Stakeholder','Channel Owner','Reviewer'], scoringEnabled:true,
  },
  {
    id:'operational-flow', name:'Operational Flow Audit', icon:'workflow', description:'Review workflows, controls, hand-offs and operating effectiveness.',
    capabilities:['questionnaire','workflow-capture','operational-data','evidence','consultant-observations','analysis','findings','recommendations','reassessment'],
    detailFields:[{id:'processName',label:'Process Name',type:'text',placeholder:'Purchase-to-Pay',required:true},{id:'processOwner',label:'Process Owner',type:'text',placeholder:'Head of Procurement',required:true},{id:'businessUnit',label:'Business Unit',type:'text',placeholder:'Corporate Services'},{id:'department',label:'Department',type:'text',placeholder:'Procurement'}],
    scopeFields:[{id:'processTrigger',label:'Process Trigger',type:'text',placeholder:'Purchase request submitted'},{id:'startPoint',label:'Start Point',type:'text',placeholder:'Purchase Request Submitted',required:true},{id:'endPoint',label:'End Point',type:'text',placeholder:'Supplier Payment Completed',required:true},{id:'processOwner',label:'Process Owner',type:'text',placeholder:'Head of Procurement'}, ...['Departments','Roles Involved','Systems Used','Inputs','Outputs','Controls','Dependencies','Locations'].map(label=>({id:label.toLowerCase().replaceAll(' ','-'),label,type:'multi-entry' as const,placeholder:`Add ${label.toLowerCase()}`})), {id:'frequency',label:'Process Frequency',type:'select',options:['Continuous','Daily','Weekly','Monthly','Quarterly','Ad hoc']},{id:'volume',label:'Approximate Volume',type:'text',placeholder:'450 transactions / month'},{id:'painPoints',label:'Known Pain Points',type:'textarea',placeholder:'Describe delays, rework, control gaps or exceptions'}],
    collectionAreas:['Questionnaires','Interviews','Process Documents','SOPs','System Screenshots','Operational Data','Observations','Policies','Controls'], supportedTabs:['Overview','Collection','Workflow','Findings','Recommendations','Actions','Evidence','Workpapers','Review','Reports','Planning','Reassessment','Activity'], compatibleFrameworks:['fwk-of-001','fwk-gov-001','fwk-hr-001','fwk-fin-001'], requiredEvidenceTypes:['Document','Data','Screenshot','File'], stakeholderLabels:['Process Owner','Subject Matter Expert','Participant','Reviewer'], scoringEnabled:false,
  },
  {
    id:'customer-experience', name:'Customer Experience Audit', icon:'customer-experience', description:'Evaluate the quality, consistency and effectiveness of the customer experience across relevant touchpoints.',
    capabilities:['questionnaire','evidence','consultant-observations','analysis','findings','recommendations','reassessment'],
    detailFields:[{id:'journeyName',label:'Customer Journey / Experience',type:'text',placeholder:'Customer onboarding',required:true},{id:'experienceOwner',label:'Experience Owner',type:'text',placeholder:'Head of Customer Experience'},{id:'primaryAudience',label:'Primary Customer Segment',type:'text',placeholder:'New business customers'}],
    scopeFields:[{id:'touchpoints',label:'Customer Touchpoints',type:'multi-select',options:['Website','Mobile App','Contact Centre','Email','Social Media','In Person','Self Service','Sales','Support','Billing','Other'],required:true},{id:'journeyStages',label:'Journey Stages',type:'multi-entry',placeholder:'Add a journey stage'},{id:'customerSegments',label:'Customer Segments',type:'multi-entry',placeholder:'Add a customer segment'},{id:'channels',label:'Channels',type:'multi-entry',placeholder:'Add a channel'},{id:'locations',label:'Locations',type:'multi-entry',placeholder:'Add a location'},{id:'knownPainPoints',label:'Known Experience Pain Points',type:'textarea',placeholder:'Describe known friction or service gaps'}],
    collectionAreas:['Experience Strategy','Customer Journey','Digital Touchpoints','Human Touchpoints','Voice of Customer','Service Consistency','Accessibility & Inclusion','Service Recovery'], supportedTabs:sharedTabs, compatibleFrameworks:[], requiredEvidenceTypes:['Document','Data','Screenshot','Observation'], stakeholderLabels:['Experience Owner','Journey Owner','Service Owner','Reviewer'], scoringEnabled:true,
  },
  {
    id:'people', name:'People Audit', icon:'people', description:'Assess people-related practices, capability, structure, processes and organisational effectiveness.',
    capabilities:['questionnaire','evidence','consultant-observations','analysis','findings','recommendations','reassessment'],
    detailFields:[{id:'peopleScope',label:'People / Workforce Scope',type:'text',placeholder:'Corporate workforce',required:true},{id:'peopleOwner',label:'People Function Owner',type:'text',placeholder:'Head of People'},{id:'businessUnit',label:'Business Unit',type:'text',placeholder:'All business units'}],
    scopeFields:[{id:'peoplePractices',label:'People Practices',type:'multi-select',options:['Workforce Planning','Recruitment','Onboarding','Performance','Learning & Development','Engagement','Wellbeing','Reward','Diversity & Inclusion','Retention','Offboarding'],required:true},{id:'departments',label:'Departments',type:'multi-entry',placeholder:'Add a department'},{id:'workforceGroups',label:'Workforce Groups',type:'multi-entry',placeholder:'Add a workforce group'},{id:'locations',label:'Locations',type:'multi-entry',placeholder:'Add a location'},{id:'systems',label:'People Systems',type:'multi-entry',placeholder:'Add a system'},{id:'knownChallenges',label:'Known People Challenges',type:'textarea',placeholder:'Describe known capability, process or organisational challenges'}],
    collectionAreas:['Workforce Planning','Organisation Design','Talent Acquisition','Onboarding','Performance & Capability','Engagement & Culture','Wellbeing & Inclusion','Reward & Retention'], supportedTabs:sharedTabs, compatibleFrameworks:[], requiredEvidenceTypes:['Document','Data','File','Observation'], stakeholderLabels:['People Owner','Business Leader','People Manager','Employee Representative','Reviewer'], scoringEnabled:true,
  },
  {
    id:'intelligence', name:'Intelligence Audit', icon:'intelligence', description:'Assess how effectively an organisation collects, manages, uses and converts information into actionable intelligence.',
    capabilities:['questionnaire','operational-data','evidence','consultant-observations','analysis','findings','recommendations','reassessment'],
    detailFields:[{id:'intelligenceObjective',label:'Intelligence Objective',type:'text',placeholder:'Improve commercial decision support',required:true},{id:'informationOwner',label:'Information Owner',type:'text',placeholder:'Head of Strategy & Insights'},{id:'decisionDomain',label:'Decision Domain',type:'text',placeholder:'Customer and market decisions'}],
    scopeFields:[{id:'informationSources',label:'Information Sources',type:'multi-select',options:['Operational Systems','Customer Data','Market Research','Financial Data','Web Analytics','Third-Party Data','Documents','Interviews','External Publications','Other'],required:true},{id:'decisionUseCases',label:'Decision Use Cases',type:'multi-entry',placeholder:'Add a decision use case'},{id:'systems',label:'Systems & Platforms',type:'multi-entry',placeholder:'Add a system'},{id:'stakeholders',label:'Intelligence Consumers',type:'multi-entry',placeholder:'Add a stakeholder group'},{id:'outputs',label:'Intelligence Outputs',type:'multi-entry',placeholder:'Add an output'},{id:'knownGaps',label:'Known Information Gaps',type:'textarea',placeholder:'Describe known quality, access, governance or adoption gaps'}],
    collectionAreas:['Information Strategy','Source Coverage','Data Quality','Information Governance','Analysis Capability','Insight Production','Decision Integration','Learning & Improvement'], supportedTabs:sharedTabs, compatibleFrameworks:[], requiredEvidenceTypes:['Data','Document','Report','File'], stakeholderLabels:['Information Owner','Data Steward','Analyst','Decision Maker','Reviewer'], scoringEnabled:true,
  },
] as const satisfies readonly AuditTypeDefinition[]

export type AuditTypeName = (typeof AUDIT_TYPES)[number]['name']
export type AuditType = (typeof AUDIT_TYPES)[number]
export const AUDIT_TYPE_NAMES = AUDIT_TYPES.map(({name})=>name)
export const AUDIT_TYPE_IDS = AUDIT_TYPES.map(({id})=>id)
export const isAuditTypeId = (value:unknown): value is (typeof AUDIT_TYPES)[number]['id'] => typeof value==='string' && AUDIT_TYPES.some(type=>type.id===value)
export const isAuditTypeName = (value:unknown): value is AuditTypeName => typeof value==='string' && AUDIT_TYPES.some(type=>type.name===value)
export const getAuditType = (id:string): AuditType => AUDIT_TYPES.find(type=>type.id===id) ?? AUDIT_TYPES[0]
export const getAuditTypeByName = (name:AuditTypeName|string): AuditType => AUDIT_TYPES.find(type=>type.name===name) ?? (name==='Brand Audit'?getAuditType('brand'):AUDIT_TYPES[0])
export function getAuditTypeFromAuditId(auditId:string){ if(auditId.includes('BRN')) return getAuditType('brand'); if(auditId.includes('DIG')||auditId.includes('SEC')) return getAuditType('digital-presence'); if(auditId.includes('OF')) return getAuditType('operational-flow'); if(auditId.includes('CX')) return getAuditType('customer-experience'); if(auditId.includes('PPL')) return getAuditType('people'); if(auditId.includes('INT')) return getAuditType('intelligence'); return getAuditType('website') }
