'use client'

import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { BarChart3, Check, Eye, EyeOff, FileCheck2, FolderOpen, LockKeyhole, Mail, RefreshCw, ShieldCheck, TimerReset } from 'lucide-react'
import { useMemo, useState } from 'react'
import { MicrosoftLogo } from '@/components/auth/microsoft-sign-in'
import { TraceLogo } from '@/components/layout/trace-logo'
import { PublicFooter } from '@/components/marketing/public-footer'
import { PLANS } from '@/config/public-site'
import { cn } from '@/lib/utils'

type Mode='sign-in'|'sign-up'
const signInValues=[[TimerReset,'Pick up where you left off','Continue your audits and never lose progress.'],[BarChart3,'Real-time insights','Track performance and improvement across all your clients.'],[FolderOpen,'All your evidence, organised','Access files, notes and screenshots instantly.'],[ShieldCheck,'Secure and reliable','Strong access controls help keep your data protected.']] as const
const signUpValues=[[ShieldCheck,'Structured audits','Run consistent, repeatable audits with powerful frameworks and templates.'],[FileCheck2,'Evidence that matters','Capture and organise evidence, files, notes and screenshots in one place.'],[BarChart3,'Actionable insights','Turn findings into clear actions and recommendations your clients can trust.'],[RefreshCw,'Measure improvement','Reassess over time and prove impact with data-driven reports.']] as const

export function PublicAuthExperience({mode}:{mode:Mode}){
 const signIn=mode==='sign-in'; const router=useRouter();
 const [showPassword,setShowPassword]=useState(false); const [plan,setPlan]=useState('professional'); const [password,setPassword]=useState(''); const [status,setStatus]=useState('');
 const requirements=useMemo(()=>[{label:'At least 8 characters',met:password.length>=8},{label:'1 uppercase letter',met:/[A-Z]/.test(password)},{label:'1 number',met:/\d/.test(password)},{label:'1 special character',met:/[^A-Za-z0-9]/.test(password)}],[password])
 const values=signIn?signInValues:signUpValues
 function handleSubmit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!signIn&&requirements.some(item=>!item.met)){setStatus('Please complete all password requirements.');return}setStatus(signIn?'Demo sign-in complete. Opening the TRACE workspace…':'Account creation is disabled in this UI preview.');if(signIn)setTimeout(()=>router.push('/audits'),350)}
 function oauth(provider:string){setStatus(`${provider} sign-in is shown for this UI preview and is not connected.`)}
 return <div className="min-h-screen bg-white">
  <header className="border-b border-border"><div className="mx-auto flex h-20 max-w-[1440px] items-center justify-between px-5 sm:px-8 lg:px-10"><Link href="/" aria-label="TRACE home"><TraceLogo width={164} height={37}/></Link><p className="hidden items-center gap-4 text-sm sm:flex">{signIn?'New to TRACE?':'Already have an account?'}<Link href={signIn?'/sign-up':'/sign-in'} className="inline-flex h-10 items-center rounded-lg border border-border px-4 font-semibold hover:bg-muted">{signIn?'Create account →':'Sign in →'}</Link></p></div></header>
  <main className="mx-auto grid max-w-[1180px] gap-12 px-5 py-14 sm:px-8 lg:grid-cols-[.8fr_1.2fr] lg:py-20">
   <section className="pt-4"><p className="text-xs font-bold uppercase tracking-[.14em] text-brand">{signIn?'Welcome back':'Create your account'}</p><h1 className="mt-5 max-w-lg text-4xl font-bold leading-[1.16] tracking-tight sm:text-5xl">{signIn?'Sign in to continue your audit journey.':'Start your audit transformation today.'}</h1><p className="mt-6 max-w-lg text-base leading-7 text-muted-foreground">{signIn?'Access your audits, evidence, reports and insights in one central place.':'Join consulting firms using TRACE to deliver consistent, high-quality audits that drive real improvement.'}</p><div className="mt-10 space-y-6">{values.map(([Icon,title,description])=><div key={title} className="flex gap-4"><span className="inline-flex size-13 shrink-0 items-center justify-center rounded-lg border border-border"><Icon className="size-6 text-brand"/></span><div><h2 className="text-sm font-bold">{title}</h2><p className="mt-1 max-w-sm text-sm leading-6 text-muted-foreground">{description}</p></div></div>)}</div><div className="mt-10 rounded-xl border border-border p-6"><span className="text-4xl font-bold text-brand">“</span><p className="mt-1 text-sm leading-6 text-muted-foreground">{signIn?'TRACE has become an essential part of our audit process. The clarity and structure it brings to our work is unmatched.':'TRACE has transformed how we run audits. It is structured, fast and gives our clients a clearer view of improvement.'}</p><p className="mt-5 text-sm font-bold">{signIn?'Velocity Logistics':'Nimbus Holdings'}</p><p className="text-xs text-muted-foreground">{signIn?'Operations Director':'Digital Agency'}</p></div><div className="mt-6 flex items-center gap-4 rounded-xl border border-border bg-muted/20 p-5"><LockKeyhole className="size-7 text-brand"/><div><p className="text-sm font-bold">Your data is secure with TRACE.</p><p className="mt-1 text-xs leading-5 text-muted-foreground">We use considered security practices to help keep your information safe.</p></div></div></section>
   <section className="rounded-xl border border-border bg-white p-6 shadow-[0_18px_60px_rgba(15,23,42,.05)] sm:p-9"><h2 className="text-3xl font-bold">{signIn?'Sign in to TRACE':'Create your account'}</h2><p className="mt-2 text-sm text-muted-foreground">{signIn?'Enter your details below to access your account.':'Fill in the details below to get started.'}</p><form onSubmit={handleSubmit} className="mt-8 space-y-6">
    {!signIn&&<><fieldset><legend className="text-xs font-bold uppercase tracking-[.1em]">Plan</legend><div className="mt-4 grid gap-3 sm:grid-cols-3">{PLANS.map(item=><label key={item.id} className={cn('relative cursor-pointer rounded-lg border p-4 transition-colors',plan===item.id?'border-brand ring-1 ring-brand':'border-border hover:border-foreground/30')}>{item.popular&&<span className="absolute -top-3 left-1/2 -translate-x-1/2 whitespace-nowrap rounded-full bg-brand px-2 py-1 text-[8px] font-bold uppercase text-white">Most Popular</span>}<span className="flex items-center gap-2 text-sm font-bold"><input type="radio" name="plan" value={item.id} checked={plan===item.id} onChange={()=>setPlan(item.id)} className="accent-orange-600"/>{item.name}</span><strong className="mt-5 block text-sm">{item.price}<span className="font-normal text-muted-foreground"> / month</span></strong><span className="mt-2 block text-xs text-muted-foreground">{item.shortClients}</span></label>)}</div></fieldset><fieldset className="space-y-4"><legend className="mb-4 text-xs font-bold uppercase tracking-[.1em]">Organisation details</legend><Field label="Organisation name" name="organisation" placeholder="e.g. Oak & Pixel" required/><Field label="Website (optional)" name="website" type="url" placeholder="https://yourcompany.co.za"/><div className="grid gap-4 sm:grid-cols-2"><SelectField label="Industry" name="industry" options={['Consulting','Digital Agency','Internal Audit','Professional Services','Other']}/><SelectField label="Country" name="country" options={['South Africa','United Kingdom','United States','Australia','Other']}/></div></fieldset><fieldset className="space-y-4"><legend className="mb-4 text-xs font-bold uppercase tracking-[.1em]">Admin account</legend><Field label="Full name" name="fullName" placeholder="e.g. Alex Reed" required/></fieldset></>}
    <Field label="Work email" name="email" type="email" placeholder="you@yourcompany.co.za" required icon={<Mail className="size-4"/>}/><div><label htmlFor={`${mode}-password`} className="mb-2 block text-sm font-medium">Password</label><div className="relative"><LockKeyhole className="absolute left-4 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><input id={`${mode}-password`} name="password" type={showPassword?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} required minLength={signIn?1:8} placeholder={signIn?'Enter your password':'Create a strong password'} className="h-14 w-full rounded-lg border border-border pl-11 pr-12 text-sm outline-none focus:border-brand focus:ring-2 focus:ring-brand/15"/><button type="button" onClick={()=>setShowPassword(v=>!v)} aria-label={showPassword?'Hide password':'Show password'} className="absolute right-4 top-1/2 -translate-y-1/2 text-muted-foreground"><Eye className={cn('size-5',showPassword&&'hidden')}/><EyeOff className={cn('size-5',!showPassword&&'hidden')}/></button></div>{!signIn&&<div className="mt-3 grid gap-2 sm:grid-cols-2">{requirements.map(item=><span key={item.label} className={cn('flex items-center gap-2 text-xs',item.met?'text-success':'text-muted-foreground')}><Check className="size-3.5"/>{item.label}</span>)}</div>}</div>
    {signIn?<div className="flex items-center justify-between gap-4 text-sm"><label className="inline-flex items-center gap-2"><input type="checkbox" className="size-4 accent-orange-600"/>Remember me</label><Link href="/forgot-password" className="font-medium text-brand hover:underline">Forgot password?</Link></div>:<label className="flex gap-3 text-xs leading-5"><input type="checkbox" required className="mt-0.5 size-4 shrink-0 accent-orange-600"/><span>I agree to TRACE&apos;s <span className="font-medium text-brand">Terms of Service</span> and <span className="font-medium text-brand">Privacy Policy</span>.</span></label>}
    <button type="submit" className="h-13 w-full rounded-lg bg-primary text-sm font-bold text-primary-foreground hover:bg-primary/85">{signIn?'Sign in':'Create Account'}</button><div className="flex items-center gap-4"><span className="h-px flex-1 bg-border"/><span className="text-[10px] font-medium uppercase text-muted-foreground">Or {signIn?'sign in':'sign up'} with</span><span className="h-px flex-1 bg-border"/></div><div className={cn('grid gap-3',!signIn&&'sm:grid-cols-2')}><button type="button" onClick={()=>oauth('Google')} className="h-13 rounded-lg border border-border text-sm font-semibold hover:bg-muted"><span className="mr-3 font-bold text-[#4285f4]">G</span>Continue with Google</button><button type="button" onClick={()=>oauth('Microsoft')} className="inline-flex h-13 items-center justify-center gap-3 rounded-lg border border-border text-sm font-semibold hover:bg-muted"><MicrosoftLogo/>Continue with Microsoft</button></div><p aria-live="polite" className={cn('min-h-5 text-center text-xs',status.includes('Please')?'text-destructive':'text-muted-foreground')}>{status}</p><p className="text-center text-sm">{signIn?"Don’t have an account?":"Already have an account?"} <Link href={signIn?'/sign-up':'/sign-in'} className="font-semibold text-brand">{signIn?'Create account →':'Sign in →'}</Link></p>
   </form></section>
  </main><PublicFooter/>
 </div>
}

function Field({label,icon,...props}:{label:string;icon?:React.ReactNode}&React.InputHTMLAttributes<HTMLInputElement>){const id=String(props.name);return <div><label htmlFor={id} className="mb-2 block text-sm font-medium">{label}</label><div className="relative">{icon&&<span className="absolute left-4 top-1/2 -translate-y-1/2 text-muted-foreground">{icon}</span>}<input id={id} className={cn('h-14 w-full rounded-lg border border-border px-4 text-sm outline-none placeholder:text-muted-foreground focus:border-brand focus:ring-2 focus:ring-brand/15',icon&&'pl-11')} {...props}/></div></div>}
function SelectField({label,name,options}:{label:string;name:string;options:string[]}){return <div><label htmlFor={name} className="mb-2 block text-sm font-medium">{label}</label><select id={name} name={name} className="h-14 w-full rounded-lg border border-border bg-white px-4 text-sm outline-none focus:border-brand" defaultValue={options[0]}>{options.map(option=><option key={option}>{option}</option>)}</select></div>}
