import { BarChart3, CheckCircle2, FileText, FolderOpen, Link2, ShieldCheck } from 'lucide-react'
import { AUDIT_TYPE_LABELS } from '@/config/public-site'
import { FinalCta, HeroActions, ProductPreview, SectionHeading, TrustStrip, marketingContainer } from '@/components/marketing/marketing-ui'

const evidence = [[FolderOpen,'Screenshots','Visual proof'],[FileText,'Files & Documents','Upload & store'],[Link2,'URLs','Link to sources'],[FileText,'Reports','Attach reports'],[ShieldCheck,'Review States','Draft to validated'],[CheckCircle2,'Validation','Approved evidence']] as const

export default function FeaturesPage() {
  return <>
    <section className="border-b border-border"><div className={`${marketingContainer} grid items-center gap-12 py-16 lg:grid-cols-[.75fr_1.25fr] lg:py-20`}><div><h1 className="text-4xl font-bold leading-tight tracking-tight sm:text-5xl">Everything you need to run serious audits</h1><p className="mt-5 text-base leading-7 text-muted-foreground">TRACE helps consulting firms standardise audits, manage frameworks, capture evidence, and measure improvement over time.</p><HeroActions/><TrustStrip/></div><ProductPreview mode="features"/></div></section>
    <section className={`${marketingContainer} space-y-5 py-16`}>
      <FeatureRow number="01" title="Structured Audits" description="Run consistent, repeatable audits across clients and frameworks."><div className="grid grid-cols-2 gap-2 xl:grid-cols-4">{AUDIT_TYPE_LABELS.map((type,index)=><div key={type} className="rounded-lg border border-border p-3"><p className="text-xs font-semibold">{type}</p><div className="mt-3 h-1.5 rounded-full bg-muted"><div className="h-full rounded-full bg-brand" style={{width:`${52+(index%4)*11}%`}}/></div><p className="mt-2 text-[10px] text-muted-foreground">{18+index*3} requirements</p></div>)}</div></FeatureRow>
      <FeatureRow number="02" title="Evidence Management" description="Capture, organise and validate evidence with full context."><div className="grid grid-cols-2 gap-2 lg:grid-cols-3">{evidence.map(([Icon,title,description])=><div key={title} className="flex items-center gap-3 rounded-lg border border-border p-3"><Icon className="size-5 text-brand"/><div><p className="text-xs font-semibold">{title}</p><p className="text-[10px] text-muted-foreground">{description}</p></div></div>)}</div></FeatureRow>
      <FeatureRow number="03" title="Frameworks & Templates" description="Use proven frameworks or build reusable templates for your firm."><div className="grid gap-3 md:grid-cols-[1fr_.9fr]"><div className="grid gap-2 sm:grid-cols-3">{['Digital Presence','Brand Standards','Operational Excellence'].map((item,i)=><div key={item} className="rounded-lg border border-border p-3"><p className="text-xs font-semibold">{item}</p><p className="mt-2 text-[10px] text-muted-foreground">Version {i+1}.{i+2} · {42+i*12} requirements</p></div>)}</div><div className="overflow-hidden rounded-lg border border-border text-[10px]"><div className="grid grid-cols-[1fr_65px_50px] bg-muted px-3 py-2 font-semibold"><span>Template</span><span>Checks</span><span>Used</span></div>{['Website Audit','People Audit','CX Assessment'].map((item,i)=><div key={item} className="grid grid-cols-[1fr_65px_50px] border-t border-border px-3 py-2"><span>{item}</span><span>{22+i*4}</span><span>{12-i*3}×</span></div>)}</div></div></FeatureRow>
      <FeatureRow number="04" title="Findings & Recommendations" description="Record findings, set priorities, and assign clear actions."><div className="grid gap-3 lg:grid-cols-[1.4fr_.6fr]"><div className="overflow-hidden rounded-lg border border-border text-[10px]"><div className="grid grid-cols-[1fr_1fr_60px_90px_70px] bg-muted px-3 py-2 font-semibold"><span>Finding</span><span>Requirement</span><span>Priority</span><span>Action Owner</span><span>Status</span></div>{[['Inconsistent logo usage','Brand standards','High','Sarah Johnson','In Progress'],['Missing meta descriptions','Digital presence','Medium','Mike Chen','Planned'],['Broken social links','Website quality','Low','Alex Rivera','Open']].map((row)=><div key={row[0]} className="grid grid-cols-[1fr_1fr_60px_90px_70px] border-t border-border px-3 py-3">{row.map((cell)=><span key={cell} className="truncate pr-2">{cell}</span>)}</div>)}</div><div className="rounded-lg border border-border p-4"><p className="text-xs font-bold">Top Recommendation</p><p className="mt-3 text-xs leading-5 text-muted-foreground">Standardise brand assets and usage guidelines across all digital channels.</p><p className="mt-4 text-xs font-semibold text-brand">View recommendations →</p></div></div></FeatureRow>
      <FeatureRow number="05" title="Reassessments & Improvement Tracking" description="Track performance over time and prove client progress."><div className="grid gap-3 md:grid-cols-[1.2fr_.55fr_.55fr]"><div className="rounded-lg border border-border p-4"><p className="text-xs font-semibold">Score Trend</p><svg viewBox="0 0 300 90" className="mt-2 h-24 w-full" role="img" aria-label="Improvement trend"><path d="M8 76L55 58L104 46L153 38L202 30L250 22L292 14" fill="none" stroke="currentColor" strokeWidth="3" className="text-brand"/><path d="M8 76L55 58L104 46L153 38L202 30L250 22L292 14L292 88L8 88Z" fill="currentColor" className="text-brand/10"/></svg></div><ScoreCard label="Baseline" score="64%"/><ScoreCard label="Reassessment" score="82%" improvement/></div></FeatureRow>
    </section>
    <section className={`${marketingContainer} py-12`}><SectionHeading title="Built for the full improvement cycle" description="From first diagnosis to measurable reassessment, TRACE keeps the work connected."/><div className="mx-auto mt-8 flex max-w-xl items-center justify-center gap-3 text-sm font-semibold text-brand"><BarChart3 className="size-5"/>Diagnose. Improve. Measure. Repeat.</div></section>
    <FinalCta title="Ready to run more consistent audits?" description="Bring your methodology, evidence and improvement tracking into one clear system."/>
  </>
}

function FeatureRow({number,title,description,children}:{number:string;title:string;description:string;children:React.ReactNode}){return <article className="grid overflow-hidden rounded-xl border border-border lg:grid-cols-[280px_1fr]"><div className="flex gap-4 border-b border-border p-6 lg:border-b-0 lg:border-r"><span className="text-sm font-bold text-brand">{number}</span><div><h2 className="text-lg font-bold">{title}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{description}</p></div></div><div className="min-w-0 p-4 sm:p-5">{children}</div></article>}
function ScoreCard({label,score,improvement=false}:{label:string;score:string;improvement?:boolean}){return <div className="rounded-lg border border-border p-4"><p className="text-xs font-semibold">{label}</p><p className="mt-6 text-3xl font-bold">{score}</p>{improvement&&<p className="mt-3 text-xs font-semibold text-success">↑ 18 points</p>}</div>}
