'use client'

/* eslint-disable @typescript-eslint/no-unused-vars */

import { useState } from 'react'
import { Activity, Bell, Check, Mail, MonitorCog, MoreHorizontal, Plus, Search, ShieldCheck, UserPlus, Users } from 'lucide-react'
import { Card, PanelHeader, StatRow } from '@/components/ui/card'
import { DonutChart } from '@/components/charts/audit-type-chart'
import { StatusBadge } from '@/components/ui/badge'
import { cn } from '@/lib/utils'
import { TeamUsersCrud } from './team-users-crud'
import { IntegrationsCrud } from './integrations-crud'

export function SettingsSection({ tab }: { tab: string }) {
  if (tab === 'Team & Users') return <TeamUsersCrud />
  if (tab === 'Integrations') return <IntegrationsCrud />
  if (tab === 'Billing & Plan') return <Billing />
  const descriptions: Record<string,string> = {
    'Audit Defaults':'Set organisation-wide defaults for new audits, scoring, evidence and workflows.',
    'Notifications':'Control how and when TRACE notifies your team about important audit activity.',
    'Security':'Manage authentication, access control, data protection and active sessions.',
    'System':'Configure organisation-wide TRACE behaviour, data management and file handling.',
  }
  return <div><div className="mb-4"><h2 className="text-lg font-semibold">{tab}</h2><p className="mt-1 text-xs text-muted-foreground">{descriptions[tab]}</p></div><GenericSettings tab={tab}/></div>
}

const team=[['Alex Reed','alex@oakandpixel.co.za','Admin','Active','20 Aug 2026, 10:42'],['Thelma Dube','thelma@oakandpixel.co.za','Audit Lead','Active','20 Aug 2026, 10:31'],['Maya Khan','maya@oakandpixel.co.za','Reviewer','Active','19 Aug 2026, 16:18'],['Daniel Mokoena','daniel@oakandpixel.co.za','Auditor','Active','19 Aug 2026, 09:04'],['Naledi Jacobs','naledi@oakandpixel.co.za','Viewer','Active','18 Aug 2026, 14:27'],['Jordan Smith','jordan@oakandpixel.co.za','Auditor','Pending','Never'],['Lebo Ndlovu','lebo@oakandpixel.co.za','Viewer','Inactive','12 Aug 2026, 11:36']]

function TeamUsers(){return <div><div className="mb-4 flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-lg font-semibold">Team &amp; Users</h2><p className="mt-1 text-xs text-muted-foreground">Manage people, roles and access to your organisation.</p></div><div className="flex gap-2"><button className="inline-flex h-9 items-center gap-2 rounded-md border border-border px-3 text-xs font-semibold"><Mail className="size-3.5"/> Invite Users</button><button className="inline-flex h-9 items-center gap-2 rounded-md bg-primary px-3 text-xs font-semibold text-primary-foreground"><Plus className="size-3.5"/> Add User</button></div></div><div className="mb-4 flex flex-wrap gap-2"><div className="flex h-9 min-w-60 flex-1 items-center gap-2 rounded-md border border-border px-3"><Search className="size-3.5 text-muted-foreground"/><span className="text-xs text-muted-foreground">Search team members…</span></div><button className="h-9 rounded-md border border-border px-3 text-xs">All roles ⌄</button><button className="h-9 rounded-md border border-border px-3 text-xs">All statuses ⌄</button></div><div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_270px]"><Card className="overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[780px] text-[11px]"><thead><tr className="border-b border-border">{['Team Member','Email','Role','Status','Last Active',''].map(x=><th key={x} className="px-4 py-3 text-left font-semibold text-foreground/70">{x}</th>)}</tr></thead><tbody>{team.map((r,i)=><tr key={r[1]} className="h-[60px] border-b border-border last:border-0"><td className="px-4"><div className="flex items-center gap-3"><span className="flex size-8 items-center justify-center rounded-full bg-slate-900 text-[10px] text-white">{r[0].split(' ').map(x=>x[0]).join('')}</span><span className="font-semibold">{r[0]}</span></div></td><td className="px-4 text-muted-foreground">{r[1]}</td><td className="px-4"><span className="rounded bg-muted px-2 py-1">{r[2]}</span></td><td className="px-4"><StatusBadge status={r[3]}/></td><td className="px-4 text-muted-foreground">{r[4]}</td><td><MoreHorizontal className="size-4"/></td></tr>)}</tbody></table></div></Card><aside className="space-y-4"><Summary title="Team Overview" total="7" stats={[['Active','5'],['Pending','1'],['Inactive','1'],['Seats used','7 / 15']]}/><RoleCard/><Card className="p-4"><h3 className="text-xs font-semibold">Invite &amp; Manage</h3><button className="mt-3 flex h-9 w-full items-center justify-center gap-2 rounded-md border border-border text-xs font-semibold"><UserPlus className="size-3.5"/> Invite by email</button><button className="mt-2 flex h-9 w-full items-center justify-center gap-2 rounded-md border border-border text-xs font-semibold"><Users className="size-3.5"/> Manage roles</button></Card></aside></div></div>}

function Integrations(){const integrations=[['ATLAS','Automated website intelligence','Connected','Last sync: 20 Aug 2026, 10:15 AM'],['UNISON','Team communication and review','Connected','12 active notification rules'],['HIVE','Evidence storage and collaboration','Connected','1.84 GB synced']];return <div><div className="mb-5"><h2 className="text-lg font-semibold">Integrations</h2><p className="mt-1 text-xs text-muted-foreground">Connect TRACE with the tools your team uses for analysis, communication and evidence.</p></div><div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_270px]"><main className="space-y-4">{integrations.map(([name,desc,status,meta],i)=><Card key={name} className="p-5"><div className="flex flex-wrap items-center gap-4"><span className={`flex size-12 items-center justify-center rounded-lg font-bold text-white ${i===0?'bg-slate-900':i===1?'bg-indigo-600':'bg-amber-500'}`}>{name[0]}</span><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><h3 className="text-base font-semibold">{name}</h3><StatusBadge status={status}/></div><p className="mt-1 text-xs text-muted-foreground">{desc}</p></div><button className="h-9 rounded-md border border-border px-4 text-xs font-semibold">Manage</button></div><div className="mt-5 grid grid-cols-2 gap-4 border-t border-border pt-4 text-[11px] md:grid-cols-4"><div><p className="text-muted-foreground">Status</p><p className="mt-1 font-semibold text-success">Operational</p></div><div><p className="text-muted-foreground">Connection</p><p className="mt-1 font-semibold">OAuth 2.0</p></div><div className="col-span-2"><p className="text-muted-foreground">Activity</p><p className="mt-1 font-semibold">{meta}</p></div></div></Card>)}</main><aside className="space-y-4"><Summary title="Integration Overview" total="3" stats={[['Connected','3'],['Issues','0'],['Available','5']]}/><Card className="p-4"><h3 className="mb-3 text-xs font-semibold">Connection Status</h3>{integrations.map(x=><div key={x[0]} className="flex items-center justify-between border-b border-border py-2.5 last:border-0"><span className="text-[11px] font-semibold">{x[0]}</span><span className="flex items-center gap-1 text-[10px] text-success"><Check className="size-3"/> Connected</span></div>)}</Card><Card className="p-4"><h3 className="text-xs font-semibold">Need another integration?</h3><p className="mt-2 text-[10px] leading-4 text-muted-foreground">Contact your TRACE administrator to request a supported connection.</p><button className="mt-3 text-[11px] font-semibold text-brand">View available integrations →</button></Card></aside></div></div>}

const sections: Record<string, {title:string;items:[string,string,string][]}[]> = {
  'Audit Defaults':[
    {title:'General Defaults',items:[['Default Audit Owner','Automatically assign a lead to new audits','Alex Reed'],['Default Audit Duration','Suggested completion window','14 days'],['Default Landing Status','Status assigned when an audit is created','Draft']]},
    {title:'Scoring & Ratings',items:[['Scoring Scale','Organisation scoring standard','0–100'],['Passing Score','Minimum acceptable audit score','70'],['Severity Model','Default finding severity scale','4 levels']]},
    {title:'Evidence Defaults',items:[['Evidence Required','Require evidence for assessed controls','Enabled'],['Auto Validation','Run supported validation checks','Enabled'],['Allowed File Size','Maximum size per evidence item','100 MB']]},
    {title:'Workflow Defaults',items:[['Reviewer Required','Require review before completion','Enabled'],['Auto-save','Save collection work automatically','Enabled'],['Reassessment Interval','Default follow-up schedule','90 days']]},
  ],
  'Notifications':[
    {title:'Notification Channels',items:[['Email Notifications','Receive important activity by email','Enabled'],['In-app Notifications','Show alerts in TRACE','Enabled'],['Weekly Digest','Receive a weekly audit summary','Enabled']]},
    {title:'Audit Activity',items:[['Audit Assigned','When an audit is assigned to you','Enabled'],['Audit Completed','When an assessment is completed','Enabled'],['Review Requested','When evidence or findings need review','Enabled'],['Reassessment Due','Before a reassessment deadline','Enabled']]},
    {title:'Evidence & Findings',items:[['Evidence Uploaded','New evidence added to your audits','Mentions only'],['Finding Updated','Changes to linked findings','Enabled'],['Recommendation Approved','Approval and rejection updates','Enabled']]},
  ],
  'Security':[
    {title:'Authentication',items:[['Multi-factor Authentication','Require MFA for organisation users','Required'],['Session Timeout','Sign users out after inactivity','30 minutes'],['Password Policy','Minimum strength and reuse controls','Strong']]},
    {title:'Access Control',items:[['Role-Based Access','Apply permissions through assigned roles','Enabled'],['Invite Approval','Admin approval for new invitations','Required'],['Viewer Downloads','Allow viewers to export evidence','Disabled']]},
    {title:'Data Protection',items:[['Encryption at Rest','Protect stored audit and evidence data','AES-256'],['Encryption in Transit','Protect network communications','TLS 1.3'],['Audit Trail','Log authenticated user activity','Enabled']]},
    {title:'Security Monitoring',items:[['Sign-in Alerts','Notify admins of unusual sign-ins','Enabled'],['Failed Attempt Lockout','Lock after repeated failures','5 attempts'],['Active Sessions','Organisation sessions currently active','7 sessions']]},
  ],
  'System':[
    {title:'System Preferences',items:[['Default Time Zone','Used for audit activity timestamps','Johannesburg'],['Date Format','Organisation display format','20 Aug 2026'],['Default Language','Interface and exports','English']]},
    {title:'Data Management',items:[['Automatic Backups','Protect organisation data daily','Enabled'],['Data Retention','Keep completed audit records','7 years'],['Export Format','Default structured export type','PDF + CSV']]},
    {title:'System Behaviour',items:[['Maintenance Notifications','Warn users before maintenance','Enabled'],['Performance Mode','Optimise large evidence collections','Automatic'],['Diagnostic Logging','Record system-level events','Enabled']]},
    {title:'File & Upload',items:[['Maximum Upload Size','Limit for individual evidence files','100 MB'],['Virus Scanning','Scan every uploaded file','Enabled'],['Allowed File Types','Organisation upload policy','18 types']]},
  ],
}

function GenericSettings({tab}:{tab:string}){const [states,setStates]=useState<Record<string,boolean>>({});const groups=sections[tab]??[];const icon=tab==='Security'?ShieldCheck:tab==='Notifications'?Bell:tab==='System'?MonitorCog:Activity;return <div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_270px]"><main className="space-y-4">{groups.map(g=><Card key={g.title}><PanelHeader title={g.title}/><div className="divide-y divide-border px-5 pb-3 pt-2">{g.items.map(([title,desc,value])=>{const key=`${g.title}:${title}`;const isToggle=['Enabled','Disabled','Required'].includes(value);const checked=states[key]??value!=='Disabled';return <div key={title} className="flex min-h-[58px] items-center gap-3 py-2"><span className="flex size-8 items-center justify-center rounded-full bg-muted">{icon&&(()=>{const Icon=icon;return <Icon className="size-3.5"/>})()}</span><div className="min-w-0 flex-1"><p className="text-xs font-medium">{title}</p><p className="mt-1 text-[10px] text-muted-foreground">{desc}</p></div>{isToggle?<button onClick={()=>setStates(s=>({...s,[key]:!checked}))} className={cn('relative h-5 w-9 rounded-full',checked?'bg-brand':'bg-slate-300')}><span className={cn('absolute top-0.5 size-4 rounded-full bg-white transition-all',checked?'left-[18px]':'left-0.5')}/></button>:<button className="min-w-24 rounded-md border border-border px-3 py-2 text-right text-[11px]">{value}⌄</button>}</div>})}</div></Card>)}</main><SettingsAside tab={tab}/></div>}

function SettingsAside({tab}:{tab:string}){return <aside className="space-y-4"><Summary title={`${tab} Overview`} total={tab==='Notifications'?'18':'100%'} stats={tab==='Security'?[['Security score','92 / 100'],['MFA adoption','100%'],['Active sessions','7']]:tab==='System'?[['System health','Operational'],['Last backup','02:15 AM'],['Storage used','5%']]:tab==='Notifications'?[['Enabled rules','18'],['Muted rules','3'],['Channels','2']]:[['Configured defaults','16'],['Required controls','8'],['Last updated','Today']]}/><Card className="p-4"><h3 className="mb-3 text-xs font-semibold">{tab==='System'?'System Health':'Quick Actions'}</h3>{(tab==='Security'?['Review active sessions','Download security log','Reset sign-in policy']:tab==='System'?['All services operational','Backups up to date','No maintenance scheduled']:tab==='Notifications'?['Send test notification','Configure quiet hours','Reset preferences']:['Copy defaults from template','Export configuration','Reset to recommended']).map(x=><button key={x} className="flex w-full items-center justify-between border-b border-border py-2.5 text-left text-[10px] last:border-0"><span>{x}</span><span>→</span></button>)}</Card><Card className="p-4"><h3 className="text-xs font-semibold">About these settings</h3><p className="mt-2 text-[10px] leading-4 text-muted-foreground">Changes are attributed to your authenticated account and recorded in the organisation activity log.</p></Card></aside>}

function Summary({title,total,stats}:{title:string;total:string;stats:[string,string][]}){return <Card className="p-4"><h3 className="text-xs font-semibold">{title}</h3><div className="my-4 flex justify-center"><div className="relative"><DonutChart data={[{label:'Ready',value:78,color:'oklch(0.58 0.17 150)'},{label:'Other',value:22,color:'oklch(0.88 0.02 250)'}]} size={92} thickness={13}/><strong className="absolute inset-0 flex items-center justify-center text-lg">{total}</strong></div></div><div className="space-y-2">{stats.map(x=><StatRow key={x[0]} label={x[0]} value={x[1]}/>)}</div></Card>}
function RoleCard(){return <Card className="p-4"><h3 className="mb-3 text-xs font-semibold">Roles</h3>{[['Admin','1'],['Audit Lead','1'],['Auditor','2'],['Reviewer','1'],['Viewer','2']].map(x=><div key={x[0]} className="flex items-center justify-between py-1.5 text-[10px]"><span>{x[0]}</span><b>{x[1]}</b></div>)}</Card>}
function Billing(){return <div><div className="mb-5"><h2 className="text-lg font-semibold">Billing &amp; Plan</h2><p className="mt-1 text-xs text-muted-foreground">Manage subscription, usage and billing information.</p></div><div className="grid gap-4 lg:grid-cols-2"><Card className="p-6"><p className="text-xs text-muted-foreground">Current plan</p><h3 className="mt-2 text-2xl font-semibold">Professional</h3><p className="mt-2 text-xs text-muted-foreground">R2,499 / month · renews 20 Sep 2026</p><button className="mt-5 rounded-md bg-primary px-4 py-2.5 text-xs font-semibold text-primary-foreground">Manage subscription</button></Card><Card className="p-6"><h3 className="text-sm font-semibold">Plan Usage</h3><div className="mt-5 space-y-4">{[['Team members','5 / 15','33%'],['Audits this month','12 / 200','6%'],['Storage','2.48 GB / 50 GB','5%']].map(x=><div key={x[0]}><div className="mb-1.5 flex justify-between text-[11px]"><span>{x[0]}</span><span>{x[1]}</span></div><div className="h-2 rounded bg-muted"><div className="h-full rounded bg-brand" style={{width:x[2]}}/></div></div>)}</div></Card></div></div>}
