'use client'

import { useRef, useState } from 'react'
import { useRouter } from 'next/navigation'
import { Activity, Camera, CheckCircle2, KeyRound, Link2, LogOut, Mail, Monitor, Plus, ShieldCheck, Smartphone } from 'lucide-react'
import { PageHeader } from '@/components/layout/page-header'
import { Card, PanelHeader, StatRow } from '@/components/ui/card'
import { ConfirmActionDialog, CrudActionMenu, CrudFormDialog, CrudToast } from '@/components/ui/crud'

export function UserProfileView(){
  const router=useRouter();const [profile,setProfile]=useState({first:'Alex',last:'Reed',email:'alex@oakandpixel.co.za',phone:'+27 82 456 7890',title:'Senior Audit Consultant',timezone:'(UTC+02:00) Johannesburg'});const [editor,setEditor]=useState<'profile'|'password'|'mfa'|'recovery'|'token'|null>(null);const [confirm,setConfirm]=useState<'disconnect'|'session'|'sessions'|'token'|'signout'|null>(null);const [linked,setLinked]=useState(true);const [tokens,setTokens]=useState([{id:'trace-cli',name:'TRACE CLI',created:'12 Aug 2026',lastUsed:'Today'}]);const [toast,setToast]=useState('');const fileRef=useRef<HTMLInputElement>(null)
  const save=(values:Record<string,string>)=>{if(editor==='profile')setProfile(values as typeof profile);if(editor==='token')setTokens(current=>[...current,{id:`token-${Date.now()}`,name:values.name,created:'Just now',lastUsed:'Never'}]);setToast(editor==='password'?'Password updated. Other sessions can now be revoked.':editor==='mfa'?'MFA preference updated.':editor==='recovery'?'Recovery email updated.':editor==='token'?'API token created. The secret is shown only by the backend.':'Profile updated successfully.')}
  const apply=()=>{if(confirm==='signout'){setConfirm(null);router.push('/sign-in');return}if(confirm==='disconnect')setLinked(false);if(confirm==='token')setTokens([]);setToast(confirm==='disconnect'?'Microsoft account disconnected.':confirm==='session'?'Session revoked.':confirm==='sessions'?'All other sessions revoked.':'API token revoked.');setConfirm(null)}
  return <div><PageHeader title="My Profile" description="Manage your personal details, account security and connected sign-in methods." action={<button onClick={()=>setConfirm('signout')} className="inline-flex h-10 items-center gap-2 rounded-md border border-destructive/30 px-4 text-xs font-semibold text-destructive"><LogOut className="size-4"/> Sign Out</button>}/><div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_300px]"><main className="space-y-4"><Card><PanelHeader title="Profile Information" action={<button onClick={()=>setEditor('profile')} className="rounded-md border border-border px-3 py-2 text-xs font-semibold">Edit Profile</button>}/><div className="p-5"><div className="flex items-center gap-5 border-b border-border pb-5"><div className="relative flex size-20 items-center justify-center rounded-full bg-slate-900 text-2xl text-white">{profile.first[0]}{profile.last[0]}<button onClick={()=>fileRef.current?.click()} aria-label="Change profile photo" className="absolute bottom-0 right-0 flex size-7 items-center justify-center rounded-full border-2 border-white bg-brand"><Camera className="size-3 text-white"/></button><input ref={fileRef} type="file" accept="image/*" className="hidden" onChange={event=>event.target.files?.[0]&&setToast('Profile photo selected for upload (UI preview only).')}/></div><div><h2 className="text-xl font-semibold">{profile.first} {profile.last}</h2><p className="mt-1 text-xs text-muted-foreground">Admin · Oak &amp; Pixel</p><span className="mt-2 inline-flex items-center gap-1 rounded bg-success-muted px-2 py-1 text-[10px] font-semibold text-success"><CheckCircle2 className="size-3"/> Verified account</span></div></div><div className="grid gap-4 pt-5 sm:grid-cols-2">{[['First Name',profile.first],['Last Name',profile.last],['Email Address',profile.email],['Phone Number',profile.phone],['Job Title',profile.title],['Time Zone',profile.timezone]].map(([label,value])=><div key={label}><p className="text-[11px] font-semibold">{label}</p><p className="mt-2 rounded-md border border-border bg-muted/20 px-3 py-3 text-xs">{value}</p></div>)}</div></div></Card>
      <Card><PanelHeader title="Password & Security"/><div className="divide-y divide-border p-5 pt-3">{[{title:'Password',detail:'Last changed 42 days ago',action:'Change password',icon:KeyRound,mode:'password' as const},{title:'Multi-factor Authentication',detail:'Authenticator app is active',action:'Manage MFA',icon:Smartphone,mode:'mfa' as const},{title:'Recovery Email',detail:'alex.recovery@outlook.com',action:'Update',icon:Mail,mode:'recovery' as const}].map(item=><div key={item.title} className="flex items-center gap-3 py-3"><span className="flex size-8 items-center justify-center rounded-full bg-muted"><item.icon className="size-3.5"/></span><div className="flex-1"><p className="text-xs font-semibold">{item.title}</p><p className="mt-1 text-[10px] text-muted-foreground">{item.detail}</p></div><button onClick={()=>setEditor(item.mode)} className="rounded-md border border-border px-3 py-2 text-[10px] font-semibold">{item.action}</button></div>)}</div></Card>
      <Card><PanelHeader title="Active Sessions" action={<button onClick={()=>setConfirm('sessions')} className="text-[10px] font-semibold text-destructive">Revoke all other sessions</button>}/><div className="divide-y divide-border px-5 pb-3">{[['This device · Windows','Johannesburg · Active now'],['Microsoft Edge · Windows','Johannesburg · 2 days ago']].map((session,index)=><div key={session[0]} className="flex items-center gap-3 py-3"><Monitor className="size-4 text-muted-foreground"/><div className="flex-1"><p className="text-xs font-semibold">{session[0]}</p><p className="mt-1 text-[10px] text-muted-foreground">{session[1]}</p></div>{index===0?<span className="text-[10px] text-success">Current</span>:<button onClick={()=>setConfirm('session')} className="text-[10px] font-semibold text-destructive">Revoke</button>}</div>)}</div></Card>
      <Card><PanelHeader title="API Tokens" action={<button onClick={()=>setEditor('token')} className="inline-flex items-center gap-1 rounded-md border border-border px-3 py-2 text-[10px] font-semibold"><Plus className="size-3"/> Create Token</button>}/><div className="px-5 pb-3">{tokens.length?tokens.map(token=><div key={token.id} className="flex items-center gap-3 border-b border-border py-3 last:border-0"><KeyRound className="size-4 text-muted-foreground"/><div className="flex-1"><p className="text-xs font-semibold">{token.name}</p><p className="mt-1 text-[10px] text-muted-foreground">Created {token.created} · Last used {token.lastUsed}</p></div><CrudActionMenu actions={[{label:'Revoke Token',kind:'delete',onSelect:()=>setConfirm('token')}]}/></div>):<p className="py-8 text-center text-xs text-muted-foreground">No API tokens.</p>}</div></Card></main>
      <aside className="space-y-4"><Card className="p-4"><h3 className="mb-4 text-xs font-semibold">Account Overview</h3><div className="space-y-2"><StatRow label="Role" value="Admin"/><StatRow label="Organisation" value="Oak & Pixel"/><StatRow label="Member since" value="12 Jan 2024"/><StatRow label="Last sign-in" value="Today, 08:42"/><StatRow label="Account status" value="Active" valueClassName="text-success"/></div></Card><Card className="p-4"><div className="flex items-center gap-2"><Activity className="size-4 text-brand"/><h3 className="text-xs font-semibold">Recent Activity</h3></div>{['Completed Website Audit','Approved recommendation','Uploaded evidence','Updated security settings'].map((item,index)=><div key={item} className="border-b border-border py-3 text-[10px] last:border-0"><p className="font-semibold">{item}</p><p className="mt-1 text-muted-foreground">{index===0?'Today':'Yesterday'} · Oak &amp; Pixel</p></div>)}</Card><Card className="p-4"><div className="flex items-center gap-2"><Link2 className="size-4 text-brand"/><h3 className="text-xs font-semibold">Linked Accounts</h3></div><div className="mt-3 flex items-center justify-between"><span className="text-[11px] font-semibold">Microsoft</span><span className={`text-[10px] ${linked?'text-success':'text-muted-foreground'}`}>{linked?'Connected':'Disconnected'}</span></div><button onClick={()=>linked?setConfirm('disconnect'):(setLinked(true),setToast('Microsoft account reconnected in UI simulation.'))} className="mt-4 w-full rounded-md border border-border py-2 text-[10px] font-semibold">{linked?'Disconnect account':'Reconnect account'}</button></Card><Card className="p-4"><div className="flex items-center gap-2 text-success"><ShieldCheck className="size-4"/><span className="text-xs font-semibold">Account protected</span></div><p className="mt-2 text-[10px] leading-4 text-muted-foreground">MFA and sign-in alerts are enabled.</p></Card></aside></div>
    <CrudFormDialog open={Boolean(editor)} onClose={()=>setEditor(null)} onSubmit={save} title={editor==='profile'?'Edit Profile':editor==='password'?'Change Password':editor==='mfa'?'Manage MFA':editor==='recovery'?'Update Recovery Email':'Create API Token'} description="Security changes are recorded in your immutable account activity." fields={editor==='profile'?[{name:'first',label:'First name',value:profile.first,required:true},{name:'last',label:'Last name',value:profile.last,required:true},{name:'email',label:'Email address',value:profile.email,required:true},{name:'phone',label:'Phone number',value:profile.phone},{name:'title',label:'Job title',value:profile.title},{name:'timezone',label:'Time zone',value:profile.timezone}]:editor==='password'?[{name:'current',label:'Current password',value:'',required:true},{name:'new',label:'New password',value:'',required:true},{name:'confirm',label:'Confirm new password',value:'',required:true}]:editor==='mfa'?[{name:'method',label:'MFA method',value:'Authenticator app',type:'select',options:['Authenticator app','Security key','SMS backup']},{name:'recovery',label:'Recovery code action',value:'Keep current codes',type:'select',options:['Keep current codes','Regenerate recovery codes']}]:editor==='recovery'?[{name:'email',label:'Recovery email',value:'alex.recovery@outlook.com',required:true}]:editor==='token'?[{name:'name',label:'Token name',value:'',required:true},{name:'scope',label:'Scope',value:'Read audits',type:'select',options:['Read audits','Read and write evidence','Export reports']}]:[]}/>
    <ConfirmActionDialog open={Boolean(confirm)} onClose={()=>setConfirm(null)} onConfirm={apply} title={confirm==='signout'?'Sign Out?':confirm==='disconnect'?'Disconnect Microsoft?':confirm==='token'?'Revoke API Token?':confirm==='sessions'?'Revoke All Other Sessions?':'Revoke Session?'} description={confirm==='signout'?'You will return to the TRACE sign-in page. Any unsaved changes will be lost.':confirm==='disconnect'?'You may need another sign-in method before your next login.':confirm==='token'?'Applications using this token will immediately lose access. The secret cannot be recovered.':'The selected session will be signed out. Your current session remains active.'} confirmLabel={confirm==='signout'?'Sign Out':confirm==='disconnect'?'Disconnect':confirm==='token'?'Revoke Token':'Revoke Session'} destructive/>
    {toast&&<CrudToast message={toast} onClose={()=>setToast('')}/>}</div>
}
