'use client'

import { Check, GripVertical, Pencil, Copy, Trash2 } from 'lucide-react'
import type { FrameworkValidationResult } from '@/types/framework'
import { Tooltip } from '@/components/ui/tooltip'

export function StepHeading({step,title,description}:{step:number;title:string;description:string}){return <div><p className="text-[10px] font-semibold uppercase tracking-widest text-brand">Step {step} of 7</p><h2 className="mt-2 text-xl font-semibold">{title}</h2><p className="mt-1 text-xs text-muted-foreground">{description}</p></div>}
export function SectionHeading({children}:{children:React.ReactNode}){return <h3 className="mb-4 mt-7 border-b border-border pb-2 text-xs font-semibold">{children}</h3>}
export function TextField({label,value,onChange,required,placeholder,type='text',wide=false,error}:{label:string;value:string|number;onChange:(value:string)=>void;required?:boolean;placeholder?:string;type?:string;wide?:boolean;error?:string}){return <label className={`text-xs font-semibold ${wide?'sm:col-span-2':''}`}>{label}{required&&<span className="text-brand"> *</span>}<input type={type} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} aria-invalid={Boolean(error)} className={`mt-2 h-10 w-full rounded-md border bg-background px-3 text-xs font-normal outline-none focus:ring-2 focus:ring-brand/15 ${error?'border-destructive':'border-border focus:border-brand'}`}/>{error&&<span className="mt-1 block text-[10px] font-normal text-destructive">{error}</span>}</label>}
export function TextAreaField({label,value,onChange,required,placeholder,wide=true}:{label:string;value:string;onChange:(value:string)=>void;required?:boolean;placeholder?:string;wide?:boolean}){return <label className={`text-xs font-semibold ${wide?'sm:col-span-2':''}`}>{label}{required&&<span className="text-brand"> *</span>}<textarea value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} className="mt-2 h-24 w-full resize-none rounded-md border border-border bg-background p-3 text-xs font-normal outline-none focus:border-brand focus:ring-2 focus:ring-brand/15"/></label>}
export function SelectField({label,value,onChange,options,required,disabled=false}:{label:string;value:string;onChange:(value:string)=>void;options:readonly string[];required?:boolean;disabled?:boolean}){return <label className="text-xs font-semibold">{label}{required&&<span className="text-brand"> *</span>}<select disabled={disabled} value={value} onChange={e=>onChange(e.target.value)} className="mt-2 h-10 w-full rounded-md border border-border bg-background px-3 text-xs font-normal disabled:bg-muted">{options.map(option=><option key={option}>{option}</option>)}</select></label>}
export function Toggle({label,description,checked,onChange,disabled=false}:{label:string;description?:string;checked:boolean;onChange:(checked:boolean)=>void;disabled?:boolean}){return <label className="flex items-center justify-between gap-4 border-b border-border py-3 last:border-0"><span><span className="block text-xs font-medium">{label}</span>{description&&<span className="mt-1 block text-[10px] text-muted-foreground">{description}</span>}</span><button type="button" role="switch" aria-checked={checked} disabled={disabled} onClick={()=>onChange(!checked)} className={`relative h-6 w-11 shrink-0 rounded-full transition ${checked?'bg-brand':'bg-slate-300'} disabled:opacity-60`}><span className={`absolute top-0.5 size-5 rounded-full bg-white shadow-sm transition-transform ${checked?'translate-x-5':'translate-x-0.5'}`}/></button></label>}
export function ActionButtons({onEdit,onDuplicate,onDelete}:{onEdit:()=>void;onDuplicate:()=>void;onDelete:()=>void}){return <div className="flex items-center gap-1"><Tooltip content="Edit"><button aria-label="Edit" onClick={onEdit} className="rounded p-2 text-muted-foreground hover:bg-muted hover:text-foreground"><Pencil className="size-3.5"/></button></Tooltip><Tooltip content="Duplicate"><button aria-label="Duplicate" onClick={onDuplicate} className="rounded p-2 text-muted-foreground hover:bg-muted hover:text-foreground"><Copy className="size-3.5"/></button></Tooltip><Tooltip content="Delete"><button aria-label="Delete" onClick={onDelete} className="rounded p-2 text-muted-foreground hover:bg-destructive/10 hover:text-destructive"><Trash2 className="size-3.5"/></button></Tooltip></div>}
export function DragHandle(){return <GripVertical className="size-4 shrink-0 cursor-grab text-muted-foreground"/>}
export function Readiness({results}:{results:FrameworkValidationResult[]}){const valid=results.filter(x=>x.valid).length;const percent=Math.round(valid/results.length*100);return <div className="rounded-lg border border-border p-5"><div className="flex items-center justify-between"><div><h3 className="text-sm font-semibold">Framework Readiness</h3><p className="mt-1 text-[10px] text-muted-foreground">Mandatory checks before publication</p></div><strong className={percent===100?'text-success':'text-brand'}>{percent}%</strong></div><div className="mt-4 h-1.5 rounded-full bg-muted"><div className={`h-full rounded-full transition-all ${percent===100?'bg-success':'bg-brand'}`} style={{width:`${percent}%`}}/></div><ul className="mt-4 space-y-2">{results.map(item=><li key={item.label} className={`flex items-start gap-2 text-[10px] ${item.valid?'text-foreground':'text-warning'}`}><span className={`mt-px flex size-4 shrink-0 items-center justify-center rounded-full ${item.valid?'bg-success-muted text-success':'bg-warning-muted text-warning'}`}>{item.valid?<Check className="size-2.5"/>:'!'}</span><span>{item.valid?item.label:item.detail||item.label}</span></li>)}</ul></div>}
