'use client'

import Link from 'next/link'
import { useState } from 'react'
import { Activity, ArrowLeft, CheckCircle2, Clock3, FilePlus2, MoreVertical, Pencil, ShieldCheck } from 'lucide-react'
import { Card, StatRow } from '@/components/ui/card'
import { Dialog } from '@/components/ui/dialog'
import { StatusBadge } from '@/components/ui/badge'
import { PageTabs } from '@/components/ui/tabs'
import { defaultFrameworkSections, initialFrameworkState } from '@/data/mock/framework-builder'
import { TextAreaField, TextField } from './framework-workflow-shared'

const tabs=['Overview','Structure','Checks','Scoring','Evidence Rules','Versions','Activity']
export function FrameworkDetailView(){const [tab,setTab]=useState('Overview');const [versionOpen,setVersionOpen]=useState(false);const [version,setVersion]=useState('v1.0');const [toast,setToast]=useState(false);const createVersion=(next:string)=>{setVersion(next);setVersionOpen(false);setToast(true);window.setTimeout(()=>setToast(false),3500)};return <div><Link href="/frameworks" className="inline-flex items-center gap-2 text-xs text-muted-foreground hover:text-foreground"><ArrowLeft className="size-3.5"/> Frameworks</Link><div className="mt-5 flex flex-wrap items-start justify-between gap-5"><div><div className="flex flex-wrap items-center gap-3"><h1 className="text-[27px] font-bold tracking-tight">HIMARK Web Audit Framework</h1><span className="rounded border border-border bg-muted px-2 py-1 text-xs">{version}</span><StatusBadge status="Active"/></div><div className="mt-3 flex flex-wrap items-center gap-3 text-xs text-muted-foreground"><span>Website Audit</span><span>•</span><span>FWK-WEB-001</span><span>•</span><span>Owner: Alex Reed</span><span>•</span><span>Updated: 20 Aug 2026</span></div></div><div className="flex flex-wrap gap-2"><Link href="/audits/new" className="inline-flex h-10 items-center gap-2 rounded-md bg-primary px-5 text-xs font-semibold text-primary-foreground"><FilePlus2 className="size-4"/> Create Audit</Link><button onClick={()=>setVersionOpen(true)} className="inline-flex h-10 items-center gap-2 rounded-md border border-border px-4 text-xs font-semibold"><Pencil className="size-3.5"/> Edit Framework</button><button aria-label="More framework actions" className="flex size-10 items-center justify-center rounded-md border border-border"><MoreVertical className="size-4"/></button></div></div><PageTabs tabs={tabs} active={tab} onChange={setTab} className="mt-7"/><div className="mt-6">{tab==='Overview'?<Overview/>:tab==='Structure'?<Structure/>:tab==='Checks'?<Checks/>:tab==='Scoring'?<Scoring/>:tab==='Evidence Rules'?<Evidence/>:tab==='Versions'?<Versions/>:<ActivityView/>}</div><FrameworkVersionModal open={versionOpen} current={version} onClose={()=>setVersionOpen(false)} onCreate={createVersion}/>{toast&&<div role="status" className="fixed bottom-6 right-6 z-[70] flex items-center gap-3 rounded-lg border border-success/25 bg-background px-4 py-3 text-xs font-semibold shadow-xl"><CheckCircle2 className="size-4 text-success"/> New framework version created.</div>}</div>}

function Overview(){return <div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_275px]"><div className="space-y-4"><div className="grid grid-cols-2 gap-3 md:grid-cols-4">{[['7','Sections'],['42','Checks'],['18','Usage'],['v1.0','Current Version']].map(([value,label])=><Card key={label} className="p-4"><p className="text-xl font-semibold">{value}</p><p className="mt-1 text-[10px] text-muted-foreground">{label}</p></Card>)}</div><Card className="p-5"><h3 className="text-sm font-semibold">Section Breakdown</h3><div className="mt-4 divide-y divide-border">{defaultFrameworkSections.map(section=><div key={section.id} className="grid grid-cols-[1fr_auto_auto] gap-5 py-3 text-xs"><div><p className="font-semibold">{section.name}</p><p className="mt-1 text-[10px] text-muted-foreground">{section.description}</p></div><span className="text-muted-foreground">{section.checks.length} checks</span><strong className="w-10 text-right">{section.weight}%</strong></div>)}</div></Card><Card className="p-5"><h3 className="text-sm font-semibold">Recent Usage</h3><div className="mt-4 divide-y divide-border">{[['Oak & Pixel Website — Aug 2026','Completed','20 Aug 2026'],['HIMARK Corporate Site Review','In Progress','18 Aug 2026'],['Northwind Web Assessment','Completed','12 Aug 2026']].map(row=><div key={row[0]} className="flex flex-wrap items-center justify-between gap-3 py-3 text-xs"><span className="font-medium">{row[0]}</span><StatusBadge status={row[1]}/><span className="text-[10px] text-muted-foreground">{row[2]}</span></div>)}</div></Card></div><aside className="space-y-4"><Card className="p-5"><div className="flex items-center gap-2"><ShieldCheck className="size-4 text-success"/><h3 className="text-sm font-semibold">Framework Health</h3></div><p className="mt-4 text-3xl font-semibold text-success">100%</p><p className="mt-1 text-[10px] text-muted-foreground">Ready and actively governed</p><div className="mt-4 space-y-2 text-[10px]">{['Structure valid','Scoring configured','Evidence rules active','Governance enabled'].map(x=><p key={x} className="flex items-center gap-2"><CheckCircle2 className="size-3 text-success"/>{x}</p>)}</div></Card><Card className="p-5"><h3 className="mb-4 text-sm font-semibold">Governance</h3><div className="space-y-3"><StatRow label="Owner" value="Alex Reed"/><StatRow label="Visibility" value="Organisation"/><StatRow label="Versioning" value="Major / Minor"/><StatRow label="Audit Trail" value="Enabled"/></div></Card></aside></div>}
function Structure(){return <Card className="p-5"><h3 className="text-sm font-semibold">Framework Structure</h3><p className="mt-1 text-[10px] text-muted-foreground">The active version is read-only. Create a new version to make structural changes.</p><div className="mt-5 space-y-2">{defaultFrameworkSections.map((section,index)=><div key={section.id} className="flex items-center gap-4 rounded-lg border border-border p-4"><span className="text-xs font-semibold text-brand">{String(index+1).padStart(2,'0')}</span><div className="flex-1"><p className="text-xs font-semibold">{section.name}</p><p className="mt-1 text-[10px] text-muted-foreground">{section.description}</p></div><span className="text-[10px] text-muted-foreground">{section.checks.length} checks</span><strong className="text-xs">{section.weight}%</strong></div>)}</div></Card>}
function Checks(){const checks=defaultFrameworkSections.flatMap(s=>s.checks.map(c=>({...c,section:s.name})));return <Card className="overflow-hidden"><div className="border-b border-border p-5"><h3 className="text-sm font-semibold">Checks & Criteria</h3><p className="mt-1 text-[10px] text-muted-foreground">42 checks in the active framework version.</p></div><div className="max-h-[620px] overflow-auto"><table className="w-full min-w-[760px] text-[10px]"><thead><tr className="border-b border-border"><th className="p-3 text-left">Check</th><th className="p-3 text-left">Section</th><th className="p-3 text-left">Method</th><th className="p-3 text-left">Weight</th><th className="p-3 text-left">Required</th></tr></thead><tbody>{checks.map(c=><tr key={c.id} className="border-b border-border"><td className="p-3"><b>{c.code}</b><p className="mt-1">{c.name}</p></td><td className="p-3">{c.section}</td><td className="p-3">{c.assessmentMethod}</td><td className="p-3">{c.weight}%</td><td className="p-3">{c.required?'Yes':'Optional'}</td></tr>)}</tbody></table></div></Card>}
function Scoring(){return <div className="grid gap-4 lg:grid-cols-2"><Card className="p-5"><h3 className="text-sm font-semibold">Weighted Score</h3><p className="mt-1 text-[10px] text-muted-foreground">Range 0–100</p><div className="mt-4 divide-y divide-border">{initialFrameworkState.scoring.bands.map(b=><div key={b.id} className="flex justify-between py-3 text-xs"><span>{b.minimum}–{b.maximum}</span><b>{b.label}</b></div>)}</div></Card><Card className="p-5"><h3 className="text-sm font-semibold">Severity Rules</h3><div className="mt-4 divide-y divide-border">{initialFrameworkState.scoring.severities.map(s=><div key={s.id} className="grid grid-cols-[1fr_auto_auto] gap-3 py-3 text-xs"><span className="font-semibold" style={{color:s.colour}}>{s.name}</span><span>{s.scoreImpact} points</span><b>{s.priority}</b></div>)}</div></Card></div>}
function Evidence(){const e=initialFrameworkState.evidence;return <Card className="p-5"><h3 className="text-sm font-semibold">Evidence Rules</h3><div className="mt-5 grid gap-4 sm:grid-cols-2"><StatRow label="Policy" value={e.policy}/><StatRow label="Minimum per failed check" value={String(e.minimumPerFailedCheck)}/><StatRow label="Evidence review" value="Required"/><StatRow label="Validation before completion" value="Required"/><StatRow label="External URLs" value="Allowed"/><StatRow label="Automated collection" value="Allowed"/></div><div className="mt-5 flex flex-wrap gap-2">{e.allowedTypes.map(x=><span key={x} className="rounded-full bg-muted px-3 py-1.5 text-[10px]">{x}</span>)}</div></Card>}
function Versions(){return <Card className="p-5"><h3 className="text-sm font-semibold">Version History</h3><div className="mt-4 divide-y divide-border">{[['v1.0','Active','Published by Alex Reed','20 Aug 2026'],['v0.9','Archived','Review candidate','18 Aug 2026'],['v0.1','Archived','Initial draft','15 Aug 2026']].map(row=><div key={row[0]} className="grid grid-cols-[70px_100px_1fr_auto] gap-4 py-4 text-xs"><b>{row[0]}</b><StatusBadge status={row[1]}/><span>{row[2]}</span><span className="text-muted-foreground">{row[3]}</span></div>)}</div></Card>}
function ActivityView(){return <Card className="p-5"><h3 className="text-sm font-semibold">Framework Activity</h3><div className="relative ml-3 mt-5 border-l border-border pl-7">{[['Alex Reed published v1.0','20 Aug 2026 · 10:42 AM'],['Thelma Dube approved the framework','20 Aug 2026 · 10:31 AM'],['Alex Reed updated evidence rules','20 Aug 2026 · 09:52 AM'],['Alex Reed created the framework','15 Aug 2026 · 09:02 AM']].map(item=><div key={item[0]} className="relative border-b border-border py-4 first:pt-0 last:border-0"><span className="absolute -left-[38px] top-4 flex size-6 items-center justify-center rounded-full border border-border bg-background"><Activity className="size-3 text-brand"/></span><p className="text-xs font-semibold">{item[0]}</p><p className="mt-1 flex items-center gap-1 text-[10px] text-muted-foreground"><Clock3 className="size-3"/>{item[1]}</p></div>)}</div></Card>}

function FrameworkVersionModal({open,current,onClose,onCreate}:{open:boolean;current:string;onClose:()=>void;onCreate:(version:string)=>void}){const [version,setVersion]=useState('v1.1');const [summary,setSummary]=useState('');const [reason,setReason]=useState('');return <Dialog open={open} onClose={onClose} title="Create New Version" description="Historical audits will continue using the unchanged active definition." className="max-w-xl"><div className="mb-5 grid grid-cols-2 gap-3 rounded-lg border border-border bg-muted/25 p-4 text-xs"><div><p className="text-[9px] text-muted-foreground">Current</p><b>{current}</b></div><div><p className="text-[9px] text-muted-foreground">New</p><b>{version}</b></div></div><div className="grid gap-4"><TextField label="Version Number" required value={version} onChange={setVersion}/><TextAreaField label="Change Summary" required value={summary} onChange={setSummary}/><TextAreaField label="Change Reason" required value={reason} onChange={setReason}/></div><div className="mt-5 flex justify-end gap-2"><button onClick={onClose} className="rounded-md border border-border px-4 py-2.5 text-xs font-semibold">Cancel</button><button disabled={!version||!summary||!reason} onClick={()=>onCreate(version)} className="rounded-md bg-primary px-4 py-2.5 text-xs font-semibold text-primary-foreground disabled:opacity-40">Create New Version</button></div></Dialog>}
