'use client'

import Link from 'next/link'
import { ArrowRight, CheckCircle2, Eye, FilePlus2 } from 'lucide-react'
import { Dialog } from '@/components/ui/dialog'
import { Card } from '@/components/ui/card'
import type { FrameworkValidationResult, FrameworkWorkflowState } from '@/types/framework'
import { Readiness, StepHeading } from './framework-workflow-shared'

export function frameworkReadiness(state:FrameworkWorkflowState):FrameworkValidationResult[]{const totalWeight=state.sections.reduce((sum,x)=>sum+x.weight,0);const allHaveChecks=state.sections.length>0&&state.sections.every(x=>x.checks.length>0);const checks=state.sections.flatMap(x=>x.checks);return [{label:'Framework details complete',valid:Boolean(state.details.name&&state.details.code&&state.details.description),detail:'Framework name, code and description are required'},{label:'Section weights total 100%',valid:totalWeight===100,detail:`Section weights total ${totalWeight}%`},{label:'All sections contain checks',valid:allHaveChecks,detail:`${state.sections.filter(x=>x.checks.length===0).length} sections contain no checks`},{label:'All required checks have scoring rules',valid:checks.filter(x=>x.required).every(x=>x.weight>0),detail:`${checks.filter(x=>x.required&&x.weight<=0).length} required checks have no scoring weight`},{label:'Evidence requirements configured',valid:Boolean(state.evidence.policy&&state.evidence.allowedTypes.length),detail:'Select an evidence policy and at least one evidence type'},{label:'Framework owner assigned',valid:Boolean(state.details.owner),detail:'Assign a framework owner'},{label:'Governance configured',valid:Boolean(state.governance.versioning&&state.governance.auditTrail),detail:'Complete governance and versioning settings'}]}

export function FrameworkReviewStep({state,onEdit}:{state:FrameworkWorkflowState;onEdit:(step:number)=>void}){const checks=state.sections.reduce((sum,x)=>sum+x.checks.length,0);const results=frameworkReadiness(state);return <div><StepHeading step={7} title="Review Framework" description="Review the framework configuration before publishing it."/><div className="mt-6 grid gap-4 xl:grid-cols-[minmax(0,1fr)_280px]"><div className="space-y-4"><SummaryCard title="Framework" onEdit={()=>onEdit(0)}><div className="grid gap-3 text-[10px] sm:grid-cols-2"><Summary label="Name" value={state.details.name||'Untitled framework'}/><Summary label="Code" value={state.details.code||'Not assigned'}/><Summary label="Audit Type" value={state.details.auditType}/><Summary label="Version" value={state.details.version}/><Summary label="Visibility" value={state.details.visibility}/><Summary label="Owner" value={state.details.owner}/></div></SummaryCard><SummaryCard title="Structure" onEdit={()=>onEdit(1)}><div className="mb-4 grid grid-cols-3 gap-3"><Metric value={state.sections.length} label="Sections"/><Metric value={checks} label="Checks"/><Metric value={`${state.sections.reduce((sum,x)=>sum+x.weight,0)}%`} label="Weight"/></div><div className="divide-y divide-border">{state.sections.map(section=><div key={section.id} className="grid grid-cols-[1fr_auto_auto] gap-4 py-2.5 text-[10px]"><span className="font-medium">{section.name}</span><span className="text-muted-foreground">{section.checks.length} checks</span><span className="w-10 text-right font-semibold">{section.weight}%</span></div>)}</div></SummaryCard><div className="grid gap-4 sm:grid-cols-3"><SummaryCard title="Scoring" onEdit={()=>onEdit(3)}><Summary label="Model" value={state.scoring.model}/><Summary label="Range" value={`${state.scoring.minimum}–${state.scoring.maximum}`}/><Summary label="Severity Levels" value={String(state.scoring.severities.length)}/></SummaryCard><SummaryCard title="Evidence" onEdit={()=>onEdit(4)}><Summary label="Policy" value={state.evidence.policy}/><Summary label="Validation" value={state.evidence.requireValidation?'Enabled':'Disabled'}/><Summary label="Allowed Types" value={String(state.evidence.allowedTypes.length)}/></SummaryCard><SummaryCard title="Governance" onEdit={()=>onEdit(5)}><Summary label="Visibility" value={state.details.visibility}/><Summary label="Versioning" value={state.governance.versioning}/><Summary label="Audit Trail" value="Enabled"/></SummaryCard></div></div><Readiness results={results}/></div></div>}

function SummaryCard({title,onEdit,children}:{title:string;onEdit:()=>void;children:React.ReactNode}){return <Card className="p-5"><div className="mb-4 flex items-center justify-between"><h3 className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">{title}</h3><button onClick={onEdit} className="text-[10px] font-semibold text-brand">Edit</button></div>{children}</Card>}
function Summary({label,value}:{label:string;value:string}){return <div className="mb-3"><p className="text-[9px] text-muted-foreground">{label}</p><p className="mt-1 text-[10px] font-semibold">{value}</p></div>}
function Metric({value,label}:{value:string|number;label:string}){return <div className="rounded-md bg-muted/50 p-3"><strong className="text-base">{value}</strong><p className="mt-1 text-[9px] text-muted-foreground">{label}</p></div>}

export function PublishFrameworkModal({open,state,onClose,onPublish,publishing}:{open:boolean;state:FrameworkWorkflowState;onClose:()=>void;onPublish:()=>void;publishing:boolean}){return <Dialog open={open} onClose={onClose} title="Publish Framework?" description={`${state.details.name} · ${state.details.version}`} className="max-w-lg"><p className="text-xs leading-5 text-muted-foreground">Once published, this version becomes available for use in TRACE audits. Future structural changes should create a new framework version.</p><div className="mt-5 flex justify-end gap-2"><button onClick={onClose} className="rounded-md border border-border px-4 py-2.5 text-xs font-semibold">Cancel</button><button disabled={publishing} onClick={onPublish} className="rounded-md bg-primary px-4 py-2.5 text-xs font-semibold text-primary-foreground disabled:opacity-60">{publishing?'Publishing…':'Publish Framework'}</button></div></Dialog>}

export function FrameworkSuccessState({state}:{state:FrameworkWorkflowState}){return <div className="mx-auto max-w-3xl py-12"><Card className="p-8 text-center sm:p-12"><span className="mx-auto flex size-14 items-center justify-center rounded-full bg-success-muted text-success"><CheckCircle2 className="size-7"/></span><p className="mt-6 text-[10px] font-semibold uppercase tracking-widest text-success">Framework Published</p><h1 className="mt-2 text-2xl font-bold">{state.details.name}</h1><p className="mx-auto mt-3 max-w-xl text-xs leading-5 text-muted-foreground">{state.details.name} {state.details.version} is now active and available for TRACE audits.</p><div className="mt-7 flex flex-wrap justify-center gap-3"><Link href={`/frameworks/${encodeURIComponent(state.details.code||'FWK-WEB-001')}`} className="inline-flex h-10 items-center gap-2 rounded-md bg-primary px-5 text-xs font-semibold text-primary-foreground"><Eye className="size-3.5"/> View Framework</Link><Link href="/audits/new" className="inline-flex h-10 items-center gap-2 rounded-md border border-border px-5 text-xs font-semibold"><FilePlus2 className="size-3.5"/> Create Audit Using Framework</Link><Link href="/frameworks" className="inline-flex h-10 items-center gap-2 rounded-md border border-border px-5 text-xs font-semibold">Back to Frameworks <ArrowRight className="size-3.5"/></Link></div></Card></div>}
