'use client'

import Link from 'next/link'
import { useState } from 'react'
import { Activity, ArrowLeft, CheckCircle2, FilePlus2, MoreVertical, Pencil } from 'lucide-react'
import { Card, StatRow } from '@/components/ui/card'
import { Dialog } from '@/components/ui/dialog'
import { StatusBadge } from '@/components/ui/badge'
import { PageTabs } from '@/components/ui/tabs'
import { initialTemplateState } from '@/data/mock/template-builder'
import { TextAreaField, TextField } from '@/components/frameworks/framework-workflow-shared'

const tabs=['Overview','Configuration','Scope','Team & Evidence','Versions','Usage','Activity']
export function TemplateDetailView(){const [tab,setTab]=useState('Overview');const [version,setVersion]=useState('v1.0');const [versionOpen,setVersionOpen]=useState(false);const [toast,setToast]=useState(false);const createVersion=(next:string)=>{setVersion(next);setVersionOpen(false);setToast(true);window.setTimeout(()=>setToast(false),3000)};return <div><Link href="/templates" className="inline-flex items-center gap-2 text-xs text-muted-foreground hover:text-foreground"><ArrowLeft className="size-3.5"/> Templates</Link><div className="mt-5 flex flex-wrap items-start justify-between gap-5"><div><div className="flex flex-wrap items-center gap-3"><h1 className="text-[27px] font-bold tracking-tight">Website Audit v1.0</h1><span className="rounded border border-border bg-muted px-2 py-1 text-xs">{version}</span><StatusBadge status="Active"/></div><div className="mt-3 flex flex-wrap items-center gap-3 text-xs text-muted-foreground"><span>Website Audit</span><span>•</span><span>TPL-WEB-001</span><span>•</span><span>Owner: Alex Reed</span><span>•</span><span>Updated: 20 Aug 2026</span></div></div><div className="flex flex-wrap gap-2"><Link href="/audits/new?template=tpl-web-001" className="inline-flex h-10 items-center gap-2 rounded-md bg-primary px-5 text-xs font-semibold text-primary-foreground"><FilePlus2 className="size-4"/> Create Audit</Link><button onClick={()=>setVersionOpen(true)} className="inline-flex h-10 items-center gap-2 rounded-md border border-border px-4 text-xs font-semibold"><Pencil className="size-3.5"/> Edit Template</button><button aria-label="More template actions" className="flex size-10 items-center justify-center rounded-md border border-border"><MoreVertical className="size-4"/></button></div></div><PageTabs tabs={tabs} active={tab} onChange={setTab} className="mt-7"/><div className="mt-6">{tab==='Overview'?<Overview/>:tab==='Configuration'?<Configuration/>:tab==='Scope'?<Scope/>:tab==='Team & Evidence'?<TeamEvidence/>:tab==='Versions'?<Versions/>:tab==='Usage'?<Usage/>:<ActivityView/>}</div><TemplateVersionModal open={versionOpen} current={version} onClose={()=>setVersionOpen(false)} onCreate={createVersion}/>{toast&&<div role="status" className="fixed bottom-6 right-6 z-[70] flex items-center gap-3 rounded-lg border border-success/25 bg-background px-4 py-3 text-xs font-semibold shadow-xl"><CheckCircle2 className="size-4 text-success"/> New template version created.</div>}</div>}

function Overview(){return <div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_275px]"><div className="space-y-4"><div className="grid grid-cols-2 gap-3 md:grid-cols-4">{[['Website Audit','Audit Type'],['HIMARK Web Audit','Framework'],['12','Usage'],['v1.0','Current Version']].map(([value,label])=><Card key={label} className="p-4"><p className="truncate text-base font-semibold">{value}</p><p className="mt-1 text-[10px] text-muted-foreground">{label}</p></Card>)}</div><Card className="p-5"><h3 className="text-sm font-semibold">Template Summary</h3><p className="mt-2 text-xs leading-5 text-muted-foreground">Standard website audit setup for performance, accessibility, SEO and technical assessment.</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><SummaryBlock title="Default audit configuration" rows={[['Priority','Medium'],['Due date','14 days'],['Assessment','Baseline'],['Status','Draft']]}/><SummaryBlock title="Scope defaults" rows={[['Crawl depth','3'],['Maximum pages','250'],['Devices','Mobile, Desktop'],['Overrides','Allowed']]}/><SummaryBlock title="Evidence policy" rows={[['Policy','Framework default'],['Review','Required'],['Default status','Needs Review'],['Allowed types','10']]}/><SummaryBlock title="Governance" rows={[['Visibility','Organisation'],['Versioning','Major / Minor'],['Audit Trail','Enabled'],['Duplicate','Allowed']]}/></div></Card><Card className="p-5"><h3 className="text-sm font-semibold">Recent Usage</h3><UsageTable compact/></Card></div><aside className="space-y-4"><Card className="p-5"><h3 className="text-sm font-semibold">Template Health</h3><p className="mt-4 text-3xl font-semibold text-success">100%</p><p className="mt-1 text-[10px] text-muted-foreground">Active and ready for audit creation</p><div className="mt-4 space-y-2 text-[10px]">{['Framework active','Scope configured','Evidence rules configured','Governance enabled'].map(x=><p key={x} className="flex items-center gap-2"><CheckCircle2 className="size-3 text-success"/>{x}</p>)}</div></Card><Card className="p-5"><h3 className="mb-4 text-sm font-semibold">Ownership</h3><div className="space-y-3"><StatRow label="Owner" value="Alex Reed"/><StatRow label="Organisation" value="Oak & Pixel"/><StatRow label="Visibility" value="Organisation"/><StatRow label="Status" value="Active"/></div></Card></aside></div>}
function SummaryBlock({title,rows}:{title:string;rows:string[][]}){return <div className="rounded-lg border border-border p-4"><h4 className="mb-3 text-xs font-semibold">{title}</h4>{rows.map(([label,value])=><div key={label} className="mb-2 flex justify-between gap-3 text-[10px] last:mb-0"><span className="text-muted-foreground">{label}</span><b>{value}</b></div>)}</div>}
function Configuration(){return <Card className="p-5"><h3 className="text-sm font-semibold">Default Audit Configuration</h3><div className="mt-5 grid gap-4 sm:grid-cols-2">{[['Default Audit Name Pattern','{Organisation} Website Audit — {Month} {Year}'],['Priority','Medium'],['Due Date','14 days after creation'],['Assessment Type','Baseline'],['Baseline Behaviour','Auto-create enabled'],['Default Status','Draft'],['Template Overrides','Allowed']].map(([label,value])=><div key={label} className="rounded-lg border border-border p-4"><p className="text-[9px] text-muted-foreground">{label}</p><p className="mt-2 text-xs font-semibold">{value}</p></div>)}</div></Card>}
function Scope(){const v=initialTemplateState.scope.values;return <Card className="p-5"><h3 className="text-sm font-semibold">Website Scope Defaults</h3><p className="mt-1 text-[10px] text-muted-foreground">Only website-audit scope fields are shown.</p><div className="mt-5 grid gap-4 sm:grid-cols-2">{[['Crawl Depth',String(v.crawlDepth)],['Maximum Pages',String(v.maximumPages)],['Include Subdomains',v.includeSubdomains?'Yes':'No'],['Follow External Links',v.followExternalLinks?'Yes':'No'],['Mobile Audit',v.mobileAudit?'Enabled':'Disabled'],['Desktop Audit',v.desktopAudit?'Enabled':'Disabled'],['Authentication Required',v.authenticationRequired?'Yes':'No'],['Scope Override','Allowed']].map(([label,value])=><div key={label} className="flex justify-between rounded-lg border border-border p-4 text-xs"><span className="text-muted-foreground">{label}</span><b>{value}</b></div>)}</div></Card>}
function TeamEvidence(){return <div className="grid gap-4 lg:grid-cols-2"><Card className="p-5"><h3 className="text-sm font-semibold">Default Participation Roles</h3><div className="mt-4 divide-y divide-border">{[['Audit Lead','Unassigned'],['Auditor / Consultant','Unassigned'],['Reviewer','Unassigned'],['Technical Owner','Organisation stakeholder']].map(([role,value])=><div key={role} className="flex justify-between py-3 text-xs"><span>{role}</span><b>{value}</b></div>)}</div></Card><Card className="p-5"><h3 className="text-sm font-semibold">Evidence Defaults</h3><div className="mt-4 space-y-3"><StatRow label="Policy" value="Framework default"/><StatRow label="Review Required" value="Yes"/><StatRow label="Default Status" value="Needs Review"/><StatRow label="Priority" value="Medium"/><StatRow label="Rule Override" value="Allowed"/></div><div className="mt-5 flex flex-wrap gap-2">{initialTemplateState.evidence.allowedTypes.map(x=><span key={x} className="rounded-full bg-muted px-2.5 py-1 text-[9px]">{x}</span>)}</div></Card></div>}
function Versions(){return <Card className="p-5"><h3 className="text-sm font-semibold">Version History</h3><p className="mt-1 text-[10px] text-muted-foreground">Historical audits remain tied to the template version used at creation.</p><div className="mt-4 divide-y divide-border">{[['v1.0','Active','20 Aug 2026','Created by Alex Reed'],['v0.9','Archived','12 Aug 2026','Created by Alex Reed']].map(row=><div key={row[0]} className="grid grid-cols-[70px_100px_120px_1fr] gap-4 py-4 text-xs"><b>{row[0]}</b><StatusBadge status={row[1]}/><span>{row[2]}</span><span className="text-muted-foreground">{row[3]}</span></div>)}</div></Card>}
function Usage(){return <Card className="p-5"><h3 className="text-sm font-semibold">Audits Created From This Template</h3><div className="mt-4"><UsageTable/></div></Card>}
function UsageTable({compact=false}:{compact?:boolean}){const rows=[['Oak & Pixel Website — Aug 2026','Oak & Pixel','20 Aug 2026','Alex Reed','v1.0','Completed'],['HIMARK Website Baseline','HIMARK','18 Aug 2026','Thelma Dube','v1.0','In Progress'],['Northwind Website Review','Northwind Co','12 Aug 2026','Alex Reed','v0.9','Completed']];return <div className="overflow-x-auto"><table className="w-full min-w-[700px] text-[10px]"><thead><tr className="border-b border-border">{['Audit','Organisation','Created On','Created By','Template Version','Status'].map(x=><th key={x} className="p-3 text-left">{x}</th>)}</tr></thead><tbody>{rows.slice(0,compact?2:rows.length).map(row=><tr key={row[0]} className="border-b border-border last:border-0">{row.map((cell,index)=><td key={cell} className="p-3">{index===5?<StatusBadge status={cell}/>:cell}</td>)}</tr>)}</tbody></table></div>}
function ActivityView(){const rows=[['Template Activated','Website Audit v1.0 activated','Alex Reed','20 Aug 2026 · 10:42 AM'],['Template Updated','Evidence defaults updated','Alex Reed','20 Aug 2026 · 10:18 AM'],['Template Shared','Shared with Oak & Pixel','Thelma Dube','19 Aug 2026 · 04:31 PM'],['Audit Created from Template','Oak & Pixel Website — Aug 2026','Alex Reed','19 Aug 2026 · 09:10 AM'],['Template Created','Initial draft created','Alex Reed','12 Aug 2026 · 08:55 AM']];return <Card className="overflow-hidden"><div className="border-b border-border p-5"><h3 className="text-sm font-semibold">Template Activity</h3></div><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-[10px]"><thead><tr className="border-b border-border"><th className="p-3 text-left">Activity</th><th className="p-3 text-left">Details</th><th className="p-3 text-left">User</th><th className="p-3 text-left">Date & Time</th></tr></thead><tbody>{rows.map(row=><tr key={row[0]+row[3]} className="border-b border-border last:border-0"><td className="p-3"><span className="flex items-center gap-2 font-semibold"><Activity className="size-3 text-brand"/>{row[0]}</span></td><td className="p-3">{row[1]}</td><td className="p-3">{row[2]}</td><td className="p-3 text-muted-foreground">{row[3]}</td></tr>)}</tbody></table></div></Card>}

function TemplateVersionModal({open,current,onClose,onCreate}:{open:boolean;current:string;onClose:()=>void;onCreate:(version:string)=>void}){const [version,setVersion]=useState('v1.1');const [summary,setSummary]=useState('');const [reason,setReason]=useState('');return <Dialog open={open} onClose={onClose} title="Create New Version" description="Historical audits remain tied to the unchanged template version they used." className="max-w-xl"><div className="mb-5 grid grid-cols-2 gap-3 rounded-lg border border-border bg-muted/25 p-4 text-xs"><div><p className="text-[9px] text-muted-foreground">Current</p><b>{current}</b></div><div><p className="text-[9px] text-muted-foreground">New</p><b>{version}</b></div></div><div className="grid gap-4"><TextField label="New Version" required value={version} onChange={setVersion}/><TextAreaField label="Change Summary" required value={summary} onChange={setSummary}/><TextAreaField label="Change Reason" required value={reason} onChange={setReason}/></div><div className="mt-5 flex justify-end gap-2"><button onClick={onClose} className="rounded-md border border-border px-4 py-2.5 text-xs font-semibold">Cancel</button><button disabled={!version||!summary||!reason} onClick={()=>onCreate(version)} className="rounded-md bg-primary px-4 py-2.5 text-xs font-semibold text-primary-foreground disabled:opacity-40">Create New Version</button></div></Dialog>}
