'use client'

import { useState } from 'react'
import { usePathname, useRouter } from 'next/navigation'
import { CalendarDays, ChevronDown, Clock3, Globe2, Pencil, Play, ShieldCheck, UserRound } from 'lucide-react'
import { StatusBadge } from '@/components/ui/badge'
import { auditWorkspaceMeta } from '@/data/mock/audit-workflows'
import { getAuditTypeFromAuditId } from '@/config/audit-types'
import { ConfirmActionDialog, CrudActionMenu, CrudFormDialog, CrudToast } from '@/components/ui/crud'

export function AuditHeader(){
  const pathname=usePathname(); const router=useRouter(); const auditId=pathname.split('/')[2]||'TRC-WEB-2026-0042'; const type=getAuditTypeFromAuditId(auditId)
  const source=auditWorkspaceMeta[auditId]??{name:`New ${type.name}`,type:type.name,scope:'Scope in progress',status:'Draft'}
  const [record,setRecord]=useState({...source,owner:'Alex Reed',dueDate:'2026-11-20',priority:'Medium',notes:''})
  const [editOpen,setEditOpen]=useState(false); const [archiveOpen,setArchiveOpen]=useState(false); const [toast,setToast]=useState('');const [detailsOpen,setDetailsOpen]=useState(false)
  const save=(values:Record<string,string>)=>{setRecord(current=>({...current,name:values.name,scope:values.scope,owner:values.owner,dueDate:values.dueDate,priority:values.priority,notes:values.notes}));setToast('Audit details updated successfully.')}
  return <div className="mb-5"><div className="flex flex-wrap items-start justify-between gap-5"><div className="min-w-0"><div className="flex flex-wrap items-center gap-3"><h1 className="text-[25px] font-bold tracking-tight sm:text-[27px]">{record.name}</h1><StatusBadge status={record.status}/></div><div className="mt-3 flex flex-wrap items-center gap-3 text-xs text-muted-foreground"><span className="flex items-center gap-1.5"><Globe2 className="size-3.5"/> {type.name}</span><span className="flex items-center gap-1.5"><ShieldCheck className="size-3.5"/> {record.scope}</span><span className="flex items-center gap-1.5"><UserRound className="size-3.5"/> {record.owner}</span><button onClick={()=>setDetailsOpen(open=>!open)} aria-expanded={detailsOpen} className="inline-flex items-center gap-1 font-medium text-foreground">{detailsOpen?'Hide':'View'} details <ChevronDown className={`size-3 transition-transform ${detailsOpen?'rotate-180':''}`}/></button></div>{detailsOpen&&<div className="mt-3 flex flex-wrap gap-x-5 gap-y-2 rounded-md border border-border bg-muted/25 px-3 py-2.5 text-[10px] text-muted-foreground"><span>ID: <b className="font-medium text-foreground">{auditId}</b></span><span className="flex items-center gap-1"><CalendarDays className="size-3"/> Created 15 Aug 2026</span><span className="flex items-center gap-1"><Clock3 className="size-3"/> Updated just now</span><span>Priority: <b className="font-medium text-foreground">{record.priority}</b></span></div>}</div><div className="flex gap-2"><button onClick={()=>setEditOpen(true)} className="hidden h-10 items-center gap-2 rounded-md border border-border px-4 text-sm font-semibold sm:flex"><Pencil className="size-4"/> Edit</button><button onClick={()=>router.push(`/audits/${auditId}/collection`)} className="flex h-10 items-center gap-2 rounded-md bg-primary px-4 text-sm font-semibold text-primary-foreground sm:px-5"><Play className="size-4"/> <span className="hidden sm:inline">{record.status==='Completed'?'Run Audit Again':'Continue Audit'}</span><span className="sm:hidden">Continue</span></button><CrudActionMenu label="More audit actions" actions={[{label:'Edit Audit Details',kind:'edit',onSelect:()=>setEditOpen(true)},{label:'Duplicate Audit Configuration',kind:'duplicate',onSelect:()=>setToast('Audit configuration duplicated as a new draft.')},{label:'View Activity',kind:'view',onSelect:()=>router.push(`/audits/${auditId}/activity`)},{label:'Archive Audit',kind:'archive',onSelect:()=>setArchiveOpen(true)}]}/></div></div>
    <CrudFormDialog open={editOpen} onClose={()=>setEditOpen(false)} onSubmit={save} title="Edit Audit Details" description="Safe metadata can be changed here. Historical results remain immutable." fields={[{name:'name',label:'Audit name',value:record.name,required:true},{name:'scope',label:'Scope',value:record.scope,required:true},{name:'owner',label:'Owner',value:record.owner,type:'select',options:['Alex Reed','Thelma Mothiba','Maya Khan']},{name:'priority',label:'Priority',value:record.priority,type:'select',options:['Low','Medium','High','Critical']},{name:'dueDate',label:'Due date',value:record.dueDate,type:'date'},{name:'notes',label:'Notes',value:record.notes,type:'textarea'}]}/>
    <ConfirmActionDialog open={archiveOpen} onClose={()=>setArchiveOpen(false)} onConfirm={()=>{setArchiveOpen(false);setToast('Audit archived. Historical records were retained.');router.push('/audits')}} title="Archive Audit?" description="The audit will become read-only. Its assessments, findings, evidence and activity will be retained for governance." confirmLabel="Archive Audit" destructive/>
    {toast&&<CrudToast message={toast} onClose={()=>setToast('')}/>}</div>
}
